@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Building ./d_lottery (id lottery) 
echo =================================== 
IF EXIST work rmdir /q /s work 
IF EXIST tests-ready rmdir /q /s tests-ready 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_all.d 


copy 01.hand 01 >nul 


copy 02.hand 02 >nul 


copy 03.hand 03 >nul 


copy 04.hand 04 >nul 


copy 05.hand 05 >nul 


g++ -I..\..\..\res\testlib -O2 gen_rand.cpp -o gen_rand.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_rand.cpp -o gen_rand.exe' returned non-zero exit code!
  goto error
)

g++ -I..\..\..\res\testlib -O2 gen_max.cpp -o gen_max.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_max.cpp -o gen_max.exe' returned non-zero exit code!
  goto error
)

g++ -I..\..\..\res\testlib -O2 gen_big_segment.cpp -o gen_big_segment.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_big_segment.cpp -o gen_big_segment.exe' returned non-zero exit code!
  goto error
)

gen_rand  2 999 200  >06
IF errorlevel 1 (
  echo 'gen_rand  2 999 200' returned non-zero exit code!
  goto error
)

gen_rand  100 100000 100  >07
IF errorlevel 1 (
  echo 'gen_rand  100 100000 100' returned non-zero exit code!
  goto error
)

gen_rand  3100 99999 1000  >08
IF errorlevel 1 (
  echo 'gen_rand  3100 99999 1000' returned non-zero exit code!
  goto error
)

gen_rand  3101 99999 5000  >09
IF errorlevel 1 (
  echo 'gen_rand  3101 99999 5000' returned non-zero exit code!
  goto error
)

gen_rand  50001 99999 7000  >10
IF errorlevel 1 (
  echo 'gen_rand  50001 99999 7000' returned non-zero exit code!
  goto error
)

gen_rand  50101 99999 9000  >11
IF errorlevel 1 (
  echo 'gen_rand  50101 99999 9000' returned non-zero exit code!
  goto error
)

gen_rand  70001 100000 10000  >12
IF errorlevel 1 (
  echo 'gen_rand  70001 100000 10000' returned non-zero exit code!
  goto error
)

gen_big_segment  1 100000000 100000  >13
IF errorlevel 1 (
  echo 'gen_big_segment  1 100000000 100000' returned non-zero exit code!
  goto error
)

gen_max   >14
IF errorlevel 1 (
  echo 'gen_max ' returned non-zero exit code!
  goto error
)

gen_rand  100000000 500000000 100000  >15
IF errorlevel 1 (
  echo 'gen_rand  100000000 500000000 100000' returned non-zero exit code!
  goto error
)

gen_rand  200000000 999999999 100000  >16
IF errorlevel 1 (
  echo 'gen_rand  200000000 999999999 100000' returned non-zero exit code!
  goto error
)

gen_rand  100000001 1000000000 100000  >17
IF errorlevel 1 (
  echo 'gen_rand  100000001 1000000000 100000' returned non-zero exit code!
  goto error
)

gen_rand  1 1000000000 99999  >18
IF errorlevel 1 (
  echo 'gen_rand  1 1000000000 99999' returned non-zero exit code!
  goto error
)

gen_rand  2 1000000000 100000  >19
IF errorlevel 1 (
  echo 'gen_rand  2 1000000000 100000' returned non-zero exit code!
  goto error
)

gen_rand  1 1000000000 100000  >20
IF errorlevel 1 (
  echo 'gen_rand  1 1000000000 100000' returned non-zero exit code!
  goto error
)

rem (End of translated text) 

echo Compiling solution, validator and checker... 
g++ -I..\..\..\res\testlib -O2 ..\lottery_el.cpp -o lottery_el.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\lottery_el.cpp -o lottery_el.exe' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 01 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 1: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 01.a >nul 
validate 01 01.a 
IF errorlevel 1 (
  echo Test 1: 'validate 01 01.a' returned non-zero exit code!
  goto error
)
check 01 lottery.out 01.a 
IF errorlevel 1 (
  echo Test 1: 'check 01 lottery.out 01.a' returned non-zero exit code!
  goto error
)

echo Test 2 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 02 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 2: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 02.a >nul 
validate 02 02.a 
IF errorlevel 1 (
  echo Test 2: 'validate 02 02.a' returned non-zero exit code!
  goto error
)
check 02 lottery.out 02.a 
IF errorlevel 1 (
  echo Test 2: 'check 02 lottery.out 02.a' returned non-zero exit code!
  goto error
)

echo Test 3 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 03 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 3: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 03.a >nul 
validate 03 03.a 
IF errorlevel 1 (
  echo Test 3: 'validate 03 03.a' returned non-zero exit code!
  goto error
)
check 03 lottery.out 03.a 
IF errorlevel 1 (
  echo Test 3: 'check 03 lottery.out 03.a' returned non-zero exit code!
  goto error
)

echo Test 4 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 04 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 4: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 04.a >nul 
validate 04 04.a 
IF errorlevel 1 (
  echo Test 4: 'validate 04 04.a' returned non-zero exit code!
  goto error
)
check 04 lottery.out 04.a 
IF errorlevel 1 (
  echo Test 4: 'check 04 lottery.out 04.a' returned non-zero exit code!
  goto error
)

echo Test 5 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 05 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 5: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 05.a >nul 
validate 05 05.a 
IF errorlevel 1 (
  echo Test 5: 'validate 05 05.a' returned non-zero exit code!
  goto error
)
check 05 lottery.out 05.a 
IF errorlevel 1 (
  echo Test 5: 'check 05 lottery.out 05.a' returned non-zero exit code!
  goto error
)

echo Test 6 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 06 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 6: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 06.a >nul 
validate 06 06.a 
IF errorlevel 1 (
  echo Test 6: 'validate 06 06.a' returned non-zero exit code!
  goto error
)
check 06 lottery.out 06.a 
IF errorlevel 1 (
  echo Test 6: 'check 06 lottery.out 06.a' returned non-zero exit code!
  goto error
)

echo Test 7 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 07 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 7: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 07.a >nul 
validate 07 07.a 
IF errorlevel 1 (
  echo Test 7: 'validate 07 07.a' returned non-zero exit code!
  goto error
)
check 07 lottery.out 07.a 
IF errorlevel 1 (
  echo Test 7: 'check 07 lottery.out 07.a' returned non-zero exit code!
  goto error
)

echo Test 8 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 08 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 8: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 08.a >nul 
validate 08 08.a 
IF errorlevel 1 (
  echo Test 8: 'validate 08 08.a' returned non-zero exit code!
  goto error
)
check 08 lottery.out 08.a 
IF errorlevel 1 (
  echo Test 8: 'check 08 lottery.out 08.a' returned non-zero exit code!
  goto error
)

echo Test 9 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 09 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 9: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 09.a >nul 
validate 09 09.a 
IF errorlevel 1 (
  echo Test 9: 'validate 09 09.a' returned non-zero exit code!
  goto error
)
check 09 lottery.out 09.a 
IF errorlevel 1 (
  echo Test 9: 'check 09 lottery.out 09.a' returned non-zero exit code!
  goto error
)

echo Test 10 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 10 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 10: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 10.a >nul 
validate 10 10.a 
IF errorlevel 1 (
  echo Test 10: 'validate 10 10.a' returned non-zero exit code!
  goto error
)
check 10 lottery.out 10.a 
IF errorlevel 1 (
  echo Test 10: 'check 10 lottery.out 10.a' returned non-zero exit code!
  goto error
)

echo Test 11 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 11 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 11: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 11.a >nul 
validate 11 11.a 
IF errorlevel 1 (
  echo Test 11: 'validate 11 11.a' returned non-zero exit code!
  goto error
)
check 11 lottery.out 11.a 
IF errorlevel 1 (
  echo Test 11: 'check 11 lottery.out 11.a' returned non-zero exit code!
  goto error
)

echo Test 12 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 12 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 12: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 12.a >nul 
validate 12 12.a 
IF errorlevel 1 (
  echo Test 12: 'validate 12 12.a' returned non-zero exit code!
  goto error
)
check 12 lottery.out 12.a 
IF errorlevel 1 (
  echo Test 12: 'check 12 lottery.out 12.a' returned non-zero exit code!
  goto error
)

echo Test 13 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 13 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 13: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 13.a >nul 
validate 13 13.a 
IF errorlevel 1 (
  echo Test 13: 'validate 13 13.a' returned non-zero exit code!
  goto error
)
check 13 lottery.out 13.a 
IF errorlevel 1 (
  echo Test 13: 'check 13 lottery.out 13.a' returned non-zero exit code!
  goto error
)

echo Test 14 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 14 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 14: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 14.a >nul 
validate 14 14.a 
IF errorlevel 1 (
  echo Test 14: 'validate 14 14.a' returned non-zero exit code!
  goto error
)
check 14 lottery.out 14.a 
IF errorlevel 1 (
  echo Test 14: 'check 14 lottery.out 14.a' returned non-zero exit code!
  goto error
)

echo Test 15 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 15 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 15: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 15.a >nul 
validate 15 15.a 
IF errorlevel 1 (
  echo Test 15: 'validate 15 15.a' returned non-zero exit code!
  goto error
)
check 15 lottery.out 15.a 
IF errorlevel 1 (
  echo Test 15: 'check 15 lottery.out 15.a' returned non-zero exit code!
  goto error
)

echo Test 16 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 16 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 16: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 16.a >nul 
validate 16 16.a 
IF errorlevel 1 (
  echo Test 16: 'validate 16 16.a' returned non-zero exit code!
  goto error
)
check 16 lottery.out 16.a 
IF errorlevel 1 (
  echo Test 16: 'check 16 lottery.out 16.a' returned non-zero exit code!
  goto error
)

echo Test 17 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 17 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 17: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 17.a >nul 
validate 17 17.a 
IF errorlevel 1 (
  echo Test 17: 'validate 17 17.a' returned non-zero exit code!
  goto error
)
check 17 lottery.out 17.a 
IF errorlevel 1 (
  echo Test 17: 'check 17 lottery.out 17.a' returned non-zero exit code!
  goto error
)

echo Test 18 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 18 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 18: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 18.a >nul 
validate 18 18.a 
IF errorlevel 1 (
  echo Test 18: 'validate 18 18.a' returned non-zero exit code!
  goto error
)
check 18 lottery.out 18.a 
IF errorlevel 1 (
  echo Test 18: 'check 18 lottery.out 18.a' returned non-zero exit code!
  goto error
)

echo Test 19 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 19 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 19: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 19.a >nul 
validate 19 19.a 
IF errorlevel 1 (
  echo Test 19: 'validate 19 19.a' returned non-zero exit code!
  goto error
)
check 19 lottery.out 19.a 
IF errorlevel 1 (
  echo Test 19: 'check 19 lottery.out 19.a' returned non-zero exit code!
  goto error
)

echo Test 20 
IF EXIST lottery.out del lottery.out >nul  
IF EXIST lottery.in del lottery.in >nul  
copy 20 lottery.in >nul 
lottery_el  
IF errorlevel 1 (
  echo Test 20: 'lottery_el ' returned non-zero exit code!
  goto error
)
copy lottery.out 20.a >nul 
validate 20 20.a 
IF errorlevel 1 (
  echo Test 20: 'validate 20 20.a' returned non-zero exit code!
  goto error
)
check 20 lottery.out 20.a 
IF errorlevel 1 (
  echo Test 20: 'check 20 lottery.out 20.a' returned non-zero exit code!
  goto error
)

echo Copying tests to tests-ready 
mkdir ..\tests-ready 
echo Test 1 
copy 01 ..\tests-ready\01 >nul 
copy 01.a ..\tests-ready\01.a >nul 
echo Test 2 
copy 02 ..\tests-ready\02 >nul 
copy 02.a ..\tests-ready\02.a >nul 
echo Test 3 
copy 03 ..\tests-ready\03 >nul 
copy 03.a ..\tests-ready\03.a >nul 
echo Test 4 
copy 04 ..\tests-ready\04 >nul 
copy 04.a ..\tests-ready\04.a >nul 
echo Test 5 
copy 05 ..\tests-ready\05 >nul 
copy 05.a ..\tests-ready\05.a >nul 
echo Test 6 
copy 06 ..\tests-ready\06 >nul 
copy 06.a ..\tests-ready\06.a >nul 
echo Test 7 
copy 07 ..\tests-ready\07 >nul 
copy 07.a ..\tests-ready\07.a >nul 
echo Test 8 
copy 08 ..\tests-ready\08 >nul 
copy 08.a ..\tests-ready\08.a >nul 
echo Test 9 
copy 09 ..\tests-ready\09 >nul 
copy 09.a ..\tests-ready\09.a >nul 
echo Test 10 
copy 10 ..\tests-ready\10 >nul 
copy 10.a ..\tests-ready\10.a >nul 
echo Test 11 
copy 11 ..\tests-ready\11 >nul 
copy 11.a ..\tests-ready\11.a >nul 
echo Test 12 
copy 12 ..\tests-ready\12 >nul 
copy 12.a ..\tests-ready\12.a >nul 
echo Test 13 
copy 13 ..\tests-ready\13 >nul 
copy 13.a ..\tests-ready\13.a >nul 
echo Test 14 
copy 14 ..\tests-ready\14 >nul 
copy 14.a ..\tests-ready\14.a >nul 
echo Test 15 
copy 15 ..\tests-ready\15 >nul 
copy 15.a ..\tests-ready\15.a >nul 
echo Test 16 
copy 16 ..\tests-ready\16 >nul 
copy 16.a ..\tests-ready\16.a >nul 
echo Test 17 
copy 17 ..\tests-ready\17 >nul 
copy 17.a ..\tests-ready\17.a >nul 
echo Test 18 
copy 18 ..\tests-ready\18 >nul 
copy 18.a ..\tests-ready\18.a >nul 
echo Test 19 
copy 19 ..\tests-ready\19 >nul 
copy 19.a ..\tests-ready\19.a >nul 
echo Test 20 
copy 20 ..\tests-ready\20 >nul 
copy 20.a ..\tests-ready\20.a >nul 
echo Problem built. 
cd .. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
