#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

echo '===================================' 
echo 'Building ./d_lottery (id lottery)' 
echo '===================================' 
rm -rf ./work 
rm -rf ./tests-ready 
mkdir work 
cp tests/* work/ 
cd work 

echo 'Running test generation script(s)...' 
# Next text has been translated from file(s) do_st.d, do_all.d


cp st01.hand 01 

cp st01.a.hand 01.a 


cp st02.hand 02 

cp st02.a.hand 02.a 



cp 01.hand 03 


cp 02.hand 04 


cp 03.hand 05 


cp 04.hand 06 


cp 05.hand 07 


g++ -I../../../res/testlib -O2 gen_rand.cpp -o gen_rand  || { echo "'g++ -I../../../res/testlib -O2 gen_rand.cpp -o gen_rand' returned non-zero exit code!" ; exit 1; }

g++ -I../../../res/testlib -O2 gen_max.cpp -o gen_max  || { echo "'g++ -I../../../res/testlib -O2 gen_max.cpp -o gen_max' returned non-zero exit code!" ; exit 1; }

g++ -I../../../res/testlib -O2 gen_big_segment.cpp -o gen_big_segment  || { echo "'g++ -I../../../res/testlib -O2 gen_big_segment.cpp -o gen_big_segment' returned non-zero exit code!" ; exit 1; }

./gen_rand  2 999 200  >08 || { echo "'./gen_rand  2 999 200' returned non-zero exit code!" ; exit 1; }

./gen_rand  100 100000 100  >09 || { echo "'./gen_rand  100 100000 100' returned non-zero exit code!" ; exit 1; }

./gen_rand  3100 99999 1000  >10 || { echo "'./gen_rand  3100 99999 1000' returned non-zero exit code!" ; exit 1; }

./gen_rand  3101 99999 5000  >11 || { echo "'./gen_rand  3101 99999 5000' returned non-zero exit code!" ; exit 1; }

./gen_rand  50001 99999 7000  >12 || { echo "'./gen_rand  50001 99999 7000' returned non-zero exit code!" ; exit 1; }

./gen_rand  50101 99999 9000  >13 || { echo "'./gen_rand  50101 99999 9000' returned non-zero exit code!" ; exit 1; }

./gen_rand  70001 100000 10000  >14 || { echo "'./gen_rand  70001 100000 10000' returned non-zero exit code!" ; exit 1; }

./gen_big_segment  1 100000000 100000  >15 || { echo "'./gen_big_segment  1 100000000 100000' returned non-zero exit code!" ; exit 1; }

./gen_max   >16 || { echo "'./gen_max ' returned non-zero exit code!" ; exit 1; }

./gen_rand  100000000 500000000 100000  >17 || { echo "'./gen_rand  100000000 500000000 100000' returned non-zero exit code!" ; exit 1; }

./gen_rand  200000000 999999999 100000  >18 || { echo "'./gen_rand  200000000 999999999 100000' returned non-zero exit code!" ; exit 1; }

./gen_rand  100000001 1000000000 100000  >19 || { echo "'./gen_rand  100000001 1000000000 100000' returned non-zero exit code!" ; exit 1; }

./gen_rand  1 1000000000 99999  >20 || { echo "'./gen_rand  1 1000000000 99999' returned non-zero exit code!" ; exit 1; }

./gen_rand  2 1000000000 100000  >21 || { echo "'./gen_rand  2 1000000000 100000' returned non-zero exit code!" ; exit 1; }

./gen_rand  1 1000000000 100000  >22 || { echo "'./gen_rand  1 1000000000 100000' returned non-zero exit code!" ; exit 1; }

# (End of translated text)

echo 'Compiling solution, validator and checker...' 
g++ -I../../../res/testlib -O2 ../lottery_el.cpp -o lottery_el  || { echo "'g++ -I../../../res/testlib -O2 ../lottery_el.cpp -o lottery_el' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr' returned non-zero exit code!" ; exit 1; }

echo 'Building answer files, validating and checking them...' 

echo 'Test 1' 
rm -f lottery.out 
rm -f lottery.in 
cp 01 lottery.in 
./lottery_el   || { echo "Test 1: './lottery_el ' returned non-zero exit code!" ; exit 1; }
./validate 01 01.a  || { echo "Test 1: './validate 01 01.a' returned non-zero exit code!" ; exit 1; }
./check 01 lottery.out 01.a  || { echo "Test 1: './check 01 lottery.out 01.a' returned non-zero exit code!" ; exit 1; }
cp 01.a _tmp.out 
./check 01 _tmp.out 01.a  || { echo "Test 1: './check 01 _tmp.out 01.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 2' 
rm -f lottery.out 
rm -f lottery.in 
cp 02 lottery.in 
./lottery_el   || { echo "Test 2: './lottery_el ' returned non-zero exit code!" ; exit 1; }
./validate 02 02.a  || { echo "Test 2: './validate 02 02.a' returned non-zero exit code!" ; exit 1; }
./check 02 lottery.out 02.a  || { echo "Test 2: './check 02 lottery.out 02.a' returned non-zero exit code!" ; exit 1; }
cp 02.a _tmp.out 
./check 02 _tmp.out 02.a  || { echo "Test 2: './check 02 _tmp.out 02.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 3' 
rm -f lottery.out 
rm -f lottery.in 
cp 03 lottery.in 
./lottery_el   || { echo "Test 3: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 03.a 
./validate 03 03.a  || { echo "Test 3: './validate 03 03.a' returned non-zero exit code!" ; exit 1; }
./check 03 lottery.out 03.a  || { echo "Test 3: './check 03 lottery.out 03.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 4' 
rm -f lottery.out 
rm -f lottery.in 
cp 04 lottery.in 
./lottery_el   || { echo "Test 4: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 04.a 
./validate 04 04.a  || { echo "Test 4: './validate 04 04.a' returned non-zero exit code!" ; exit 1; }
./check 04 lottery.out 04.a  || { echo "Test 4: './check 04 lottery.out 04.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 5' 
rm -f lottery.out 
rm -f lottery.in 
cp 05 lottery.in 
./lottery_el   || { echo "Test 5: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 05.a 
./validate 05 05.a  || { echo "Test 5: './validate 05 05.a' returned non-zero exit code!" ; exit 1; }
./check 05 lottery.out 05.a  || { echo "Test 5: './check 05 lottery.out 05.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 6' 
rm -f lottery.out 
rm -f lottery.in 
cp 06 lottery.in 
./lottery_el   || { echo "Test 6: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 06.a 
./validate 06 06.a  || { echo "Test 6: './validate 06 06.a' returned non-zero exit code!" ; exit 1; }
./check 06 lottery.out 06.a  || { echo "Test 6: './check 06 lottery.out 06.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 7' 
rm -f lottery.out 
rm -f lottery.in 
cp 07 lottery.in 
./lottery_el   || { echo "Test 7: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 07.a 
./validate 07 07.a  || { echo "Test 7: './validate 07 07.a' returned non-zero exit code!" ; exit 1; }
./check 07 lottery.out 07.a  || { echo "Test 7: './check 07 lottery.out 07.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 8' 
rm -f lottery.out 
rm -f lottery.in 
cp 08 lottery.in 
./lottery_el   || { echo "Test 8: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 08.a 
./validate 08 08.a  || { echo "Test 8: './validate 08 08.a' returned non-zero exit code!" ; exit 1; }
./check 08 lottery.out 08.a  || { echo "Test 8: './check 08 lottery.out 08.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 9' 
rm -f lottery.out 
rm -f lottery.in 
cp 09 lottery.in 
./lottery_el   || { echo "Test 9: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 09.a 
./validate 09 09.a  || { echo "Test 9: './validate 09 09.a' returned non-zero exit code!" ; exit 1; }
./check 09 lottery.out 09.a  || { echo "Test 9: './check 09 lottery.out 09.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 10' 
rm -f lottery.out 
rm -f lottery.in 
cp 10 lottery.in 
./lottery_el   || { echo "Test 10: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 10.a 
./validate 10 10.a  || { echo "Test 10: './validate 10 10.a' returned non-zero exit code!" ; exit 1; }
./check 10 lottery.out 10.a  || { echo "Test 10: './check 10 lottery.out 10.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 11' 
rm -f lottery.out 
rm -f lottery.in 
cp 11 lottery.in 
./lottery_el   || { echo "Test 11: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 11.a 
./validate 11 11.a  || { echo "Test 11: './validate 11 11.a' returned non-zero exit code!" ; exit 1; }
./check 11 lottery.out 11.a  || { echo "Test 11: './check 11 lottery.out 11.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 12' 
rm -f lottery.out 
rm -f lottery.in 
cp 12 lottery.in 
./lottery_el   || { echo "Test 12: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 12.a 
./validate 12 12.a  || { echo "Test 12: './validate 12 12.a' returned non-zero exit code!" ; exit 1; }
./check 12 lottery.out 12.a  || { echo "Test 12: './check 12 lottery.out 12.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 13' 
rm -f lottery.out 
rm -f lottery.in 
cp 13 lottery.in 
./lottery_el   || { echo "Test 13: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 13.a 
./validate 13 13.a  || { echo "Test 13: './validate 13 13.a' returned non-zero exit code!" ; exit 1; }
./check 13 lottery.out 13.a  || { echo "Test 13: './check 13 lottery.out 13.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 14' 
rm -f lottery.out 
rm -f lottery.in 
cp 14 lottery.in 
./lottery_el   || { echo "Test 14: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 14.a 
./validate 14 14.a  || { echo "Test 14: './validate 14 14.a' returned non-zero exit code!" ; exit 1; }
./check 14 lottery.out 14.a  || { echo "Test 14: './check 14 lottery.out 14.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 15' 
rm -f lottery.out 
rm -f lottery.in 
cp 15 lottery.in 
./lottery_el   || { echo "Test 15: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 15.a 
./validate 15 15.a  || { echo "Test 15: './validate 15 15.a' returned non-zero exit code!" ; exit 1; }
./check 15 lottery.out 15.a  || { echo "Test 15: './check 15 lottery.out 15.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 16' 
rm -f lottery.out 
rm -f lottery.in 
cp 16 lottery.in 
./lottery_el   || { echo "Test 16: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 16.a 
./validate 16 16.a  || { echo "Test 16: './validate 16 16.a' returned non-zero exit code!" ; exit 1; }
./check 16 lottery.out 16.a  || { echo "Test 16: './check 16 lottery.out 16.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 17' 
rm -f lottery.out 
rm -f lottery.in 
cp 17 lottery.in 
./lottery_el   || { echo "Test 17: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 17.a 
./validate 17 17.a  || { echo "Test 17: './validate 17 17.a' returned non-zero exit code!" ; exit 1; }
./check 17 lottery.out 17.a  || { echo "Test 17: './check 17 lottery.out 17.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 18' 
rm -f lottery.out 
rm -f lottery.in 
cp 18 lottery.in 
./lottery_el   || { echo "Test 18: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 18.a 
./validate 18 18.a  || { echo "Test 18: './validate 18 18.a' returned non-zero exit code!" ; exit 1; }
./check 18 lottery.out 18.a  || { echo "Test 18: './check 18 lottery.out 18.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 19' 
rm -f lottery.out 
rm -f lottery.in 
cp 19 lottery.in 
./lottery_el   || { echo "Test 19: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 19.a 
./validate 19 19.a  || { echo "Test 19: './validate 19 19.a' returned non-zero exit code!" ; exit 1; }
./check 19 lottery.out 19.a  || { echo "Test 19: './check 19 lottery.out 19.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 20' 
rm -f lottery.out 
rm -f lottery.in 
cp 20 lottery.in 
./lottery_el   || { echo "Test 20: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 20.a 
./validate 20 20.a  || { echo "Test 20: './validate 20 20.a' returned non-zero exit code!" ; exit 1; }
./check 20 lottery.out 20.a  || { echo "Test 20: './check 20 lottery.out 20.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 21' 
rm -f lottery.out 
rm -f lottery.in 
cp 21 lottery.in 
./lottery_el   || { echo "Test 21: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 21.a 
./validate 21 21.a  || { echo "Test 21: './validate 21 21.a' returned non-zero exit code!" ; exit 1; }
./check 21 lottery.out 21.a  || { echo "Test 21: './check 21 lottery.out 21.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 22' 
rm -f lottery.out 
rm -f lottery.in 
cp 22 lottery.in 
./lottery_el   || { echo "Test 22: './lottery_el ' returned non-zero exit code!" ; exit 1; }
cp lottery.out 22.a 
./validate 22 22.a  || { echo "Test 22: './validate 22 22.a' returned non-zero exit code!" ; exit 1; }
./check 22 lottery.out 22.a  || { echo "Test 22: './check 22 lottery.out 22.a' returned non-zero exit code!" ; exit 1; }

echo 'Copying tests to tests-ready' 
mkdir ../tests-ready 
echo 'Test 1' 
cp 01 ../tests-ready/01 
cp 01.a ../tests-ready/01.a 
echo 'Test 2' 
cp 02 ../tests-ready/02 
cp 02.a ../tests-ready/02.a 
echo 'Test 3' 
cp 03 ../tests-ready/03 
cp 03.a ../tests-ready/03.a 
echo 'Test 4' 
cp 04 ../tests-ready/04 
cp 04.a ../tests-ready/04.a 
echo 'Test 5' 
cp 05 ../tests-ready/05 
cp 05.a ../tests-ready/05.a 
echo 'Test 6' 
cp 06 ../tests-ready/06 
cp 06.a ../tests-ready/06.a 
echo 'Test 7' 
cp 07 ../tests-ready/07 
cp 07.a ../tests-ready/07.a 
echo 'Test 8' 
cp 08 ../tests-ready/08 
cp 08.a ../tests-ready/08.a 
echo 'Test 9' 
cp 09 ../tests-ready/09 
cp 09.a ../tests-ready/09.a 
echo 'Test 10' 
cp 10 ../tests-ready/10 
cp 10.a ../tests-ready/10.a 
echo 'Test 11' 
cp 11 ../tests-ready/11 
cp 11.a ../tests-ready/11.a 
echo 'Test 12' 
cp 12 ../tests-ready/12 
cp 12.a ../tests-ready/12.a 
echo 'Test 13' 
cp 13 ../tests-ready/13 
cp 13.a ../tests-ready/13.a 
echo 'Test 14' 
cp 14 ../tests-ready/14 
cp 14.a ../tests-ready/14.a 
echo 'Test 15' 
cp 15 ../tests-ready/15 
cp 15.a ../tests-ready/15.a 
echo 'Test 16' 
cp 16 ../tests-ready/16 
cp 16.a ../tests-ready/16.a 
echo 'Test 17' 
cp 17 ../tests-ready/17 
cp 17.a ../tests-ready/17.a 
echo 'Test 18' 
cp 18 ../tests-ready/18 
cp 18.a ../tests-ready/18.a 
echo 'Test 19' 
cp 19 ../tests-ready/19 
cp 19.a ../tests-ready/19.a 
echo 'Test 20' 
cp 20 ../tests-ready/20 
cp 20.a ../tests-ready/20.a 
echo 'Test 21' 
cp 21 ../tests-ready/21 
cp 21.a ../tests-ready/21.a 
echo 'Test 22' 
cp 22 ../tests-ready/22 
cp 22.a ../tests-ready/22.a 
echo 'Problem built.' 
cd .. 
