@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Making examples for statements for  . (id classics) 
echo =================================== 
echo Building examples 
IF EXIST work rmdir /q /s work 
IF EXIST statement\examples rmdir /q /s statement\examples 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_st.d 


copy st01.hand _001.in >nul 

copy st01.hand.a _001.ans >nul 


copy st02.hand _002.in >nul 

copy st02.hand.a _002.ans >nul 


copy st03.hand _003.in >nul 

copy st03.hand.a _003.ans >nul 


copy st04.hand _004.in >nul 

copy st04.hand.a _004.ans >nul 


rem (End of translated text) 

echo Compiling solution, validator and checker... 
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\classics_pk.pas 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\classics_pk.pas' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST classics.out del classics.out >nul  
IF EXIST classics.in del classics.in >nul  
copy _001.in classics.in >nul 
classics_pk  
IF errorlevel 1 (
  echo Test 1: 'classics_pk ' returned non-zero exit code!
  goto error
)
validate _001.in _001.ans 
IF errorlevel 1 (
  echo Test 1: 'validate _001.in _001.ans' returned non-zero exit code!
  goto error
)
check _001.in classics.out _001.ans 
IF errorlevel 1 (
  echo Test 1: 'check _001.in classics.out _001.ans' returned non-zero exit code!
  goto error
)
copy _001.ans _tmp.out >nul 
check _001.in _tmp.out _001.ans 
IF errorlevel 1 (
  echo Test 1: 'check _001.in _tmp.out _001.ans' returned non-zero exit code!
  goto error
)

echo Test 2 
IF EXIST classics.out del classics.out >nul  
IF EXIST classics.in del classics.in >nul  
copy _002.in classics.in >nul 
classics_pk  
IF errorlevel 1 (
  echo Test 2: 'classics_pk ' returned non-zero exit code!
  goto error
)
validate _002.in _002.ans 
IF errorlevel 1 (
  echo Test 2: 'validate _002.in _002.ans' returned non-zero exit code!
  goto error
)
check _002.in classics.out _002.ans 
IF errorlevel 1 (
  echo Test 2: 'check _002.in classics.out _002.ans' returned non-zero exit code!
  goto error
)
copy _002.ans _tmp.out >nul 
check _002.in _tmp.out _002.ans 
IF errorlevel 1 (
  echo Test 2: 'check _002.in _tmp.out _002.ans' returned non-zero exit code!
  goto error
)

echo Test 3 
IF EXIST classics.out del classics.out >nul  
IF EXIST classics.in del classics.in >nul  
copy _003.in classics.in >nul 
classics_pk  
IF errorlevel 1 (
  echo Test 3: 'classics_pk ' returned non-zero exit code!
  goto error
)
validate _003.in _003.ans 
IF errorlevel 1 (
  echo Test 3: 'validate _003.in _003.ans' returned non-zero exit code!
  goto error
)
check _003.in classics.out _003.ans 
IF errorlevel 1 (
  echo Test 3: 'check _003.in classics.out _003.ans' returned non-zero exit code!
  goto error
)
copy _003.ans _tmp.out >nul 
check _003.in _tmp.out _003.ans 
IF errorlevel 1 (
  echo Test 3: 'check _003.in _tmp.out _003.ans' returned non-zero exit code!
  goto error
)

echo Test 4 
IF EXIST classics.out del classics.out >nul  
IF EXIST classics.in del classics.in >nul  
copy _004.in classics.in >nul 
classics_pk  
IF errorlevel 1 (
  echo Test 4: 'classics_pk ' returned non-zero exit code!
  goto error
)
validate _004.in _004.ans 
IF errorlevel 1 (
  echo Test 4: 'validate _004.in _004.ans' returned non-zero exit code!
  goto error
)
check _004.in classics.out _004.ans 
IF errorlevel 1 (
  echo Test 4: 'check _004.in classics.out _004.ans' returned non-zero exit code!
  goto error
)
copy _004.ans _tmp.out >nul 
check _004.in _tmp.out _004.ans 
IF errorlevel 1 (
  echo Test 4: 'check _004.in _tmp.out _004.ans' returned non-zero exit code!
  goto error
)

echo Copying tests to statement/examples 
mkdir ..\statement\examples 
echo Test 1 
copy _001.in ..\statement\examples\_001.in >nul 
copy _001.ans ..\statement\examples\_001.ans >nul 
echo Test 2 
copy _002.in ..\statement\examples\_002.in >nul 
copy _002.ans ..\statement\examples\_002.ans >nul 
echo Test 3 
copy _003.in ..\statement\examples\_003.in >nul 
copy _003.ans ..\statement\examples\_003.ans >nul 
echo Test 4 
copy _004.in ..\statement\examples\_004.in >nul 
copy _004.ans ..\statement\examples\_004.ans >nul 
echo Problem built. 
cd .. 
echo \FilesWithExample{examples/_001.in}{examples/_001.ans}\FilesWithExample{examples/_002.in}{examples/_002.ans}\FilesWithExample{examples/_003.in}{examples/_003.ans}\FilesWithExample{examples/_004.in}{examples/_004.ans}%%  >statement/_examples.tex
echo Examples created. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
