#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

rm -rf ./work 
mkdir work 
cd work 
echo 'Compiling solution and checker' 
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../trains_pk_wrong_int.pas  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../trains_pk_wrong_int.pas' returned non-zero exit code!" ; exit 1; }
g++ -I../../../res/testlib -O2 ../check.cpp -o check  || { echo "'g++ -I../../../res/testlib -O2 ../check.cpp -o check' returned non-zero exit code!" ; exit 1; }

echo '' 
echo 'Checking solution' 

echo 'Test 1' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/01 trains.in 
./trains_pk_wrong_int   || { echo "Test 1: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/01 trains.out ../tests-ready/01.a  || { echo "Test 1: './check ../tests-ready/01 trains.out ../tests-ready/01.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 2' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/02 trains.in 
./trains_pk_wrong_int   || { echo "Test 2: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/02 trains.out ../tests-ready/02.a  || { echo "Test 2: './check ../tests-ready/02 trains.out ../tests-ready/02.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 3' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/03 trains.in 
./trains_pk_wrong_int   || { echo "Test 3: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/03 trains.out ../tests-ready/03.a  || { echo "Test 3: './check ../tests-ready/03 trains.out ../tests-ready/03.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 4' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/04 trains.in 
./trains_pk_wrong_int   || { echo "Test 4: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/04 trains.out ../tests-ready/04.a  || { echo "Test 4: './check ../tests-ready/04 trains.out ../tests-ready/04.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 5' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/05 trains.in 
./trains_pk_wrong_int   || { echo "Test 5: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/05 trains.out ../tests-ready/05.a  || { echo "Test 5: './check ../tests-ready/05 trains.out ../tests-ready/05.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 6' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/06 trains.in 
./trains_pk_wrong_int   || { echo "Test 6: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/06 trains.out ../tests-ready/06.a  || { echo "Test 6: './check ../tests-ready/06 trains.out ../tests-ready/06.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 7' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/07 trains.in 
./trains_pk_wrong_int   || { echo "Test 7: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/07 trains.out ../tests-ready/07.a  || { echo "Test 7: './check ../tests-ready/07 trains.out ../tests-ready/07.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 8' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/08 trains.in 
./trains_pk_wrong_int   || { echo "Test 8: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/08 trains.out ../tests-ready/08.a  || { echo "Test 8: './check ../tests-ready/08 trains.out ../tests-ready/08.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 9' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/09 trains.in 
./trains_pk_wrong_int   || { echo "Test 9: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/09 trains.out ../tests-ready/09.a  || { echo "Test 9: './check ../tests-ready/09 trains.out ../tests-ready/09.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 10' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/10 trains.in 
./trains_pk_wrong_int   || { echo "Test 10: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/10 trains.out ../tests-ready/10.a  || { echo "Test 10: './check ../tests-ready/10 trains.out ../tests-ready/10.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 11' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/11 trains.in 
./trains_pk_wrong_int   || { echo "Test 11: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/11 trains.out ../tests-ready/11.a  || { echo "Test 11: './check ../tests-ready/11 trains.out ../tests-ready/11.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 12' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/12 trains.in 
./trains_pk_wrong_int   || { echo "Test 12: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/12 trains.out ../tests-ready/12.a  || { echo "Test 12: './check ../tests-ready/12 trains.out ../tests-ready/12.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 13' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/13 trains.in 
./trains_pk_wrong_int   || { echo "Test 13: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/13 trains.out ../tests-ready/13.a  || { echo "Test 13: './check ../tests-ready/13 trains.out ../tests-ready/13.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 14' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/14 trains.in 
./trains_pk_wrong_int   || { echo "Test 14: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/14 trains.out ../tests-ready/14.a  || { echo "Test 14: './check ../tests-ready/14 trains.out ../tests-ready/14.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 15' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/15 trains.in 
./trains_pk_wrong_int   || { echo "Test 15: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/15 trains.out ../tests-ready/15.a  || { echo "Test 15: './check ../tests-ready/15 trains.out ../tests-ready/15.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 16' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/16 trains.in 
./trains_pk_wrong_int   || { echo "Test 16: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/16 trains.out ../tests-ready/16.a  || { echo "Test 16: './check ../tests-ready/16 trains.out ../tests-ready/16.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 17' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/17 trains.in 
./trains_pk_wrong_int   || { echo "Test 17: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/17 trains.out ../tests-ready/17.a  || { echo "Test 17: './check ../tests-ready/17 trains.out ../tests-ready/17.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 18' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/18 trains.in 
./trains_pk_wrong_int   || { echo "Test 18: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/18 trains.out ../tests-ready/18.a  || { echo "Test 18: './check ../tests-ready/18 trains.out ../tests-ready/18.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 19' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/19 trains.in 
./trains_pk_wrong_int   || { echo "Test 19: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/19 trains.out ../tests-ready/19.a  || { echo "Test 19: './check ../tests-ready/19 trains.out ../tests-ready/19.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 20' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/20 trains.in 
./trains_pk_wrong_int   || { echo "Test 20: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/20 trains.out ../tests-ready/20.a  || { echo "Test 20: './check ../tests-ready/20 trains.out ../tests-ready/20.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 21' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/21 trains.in 
./trains_pk_wrong_int   || { echo "Test 21: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/21 trains.out ../tests-ready/21.a  || { echo "Test 21: './check ../tests-ready/21 trains.out ../tests-ready/21.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 22' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/22 trains.in 
./trains_pk_wrong_int   || { echo "Test 22: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/22 trains.out ../tests-ready/22.a  || { echo "Test 22: './check ../tests-ready/22 trains.out ../tests-ready/22.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 23' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/23 trains.in 
./trains_pk_wrong_int   || { echo "Test 23: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/23 trains.out ../tests-ready/23.a  || { echo "Test 23: './check ../tests-ready/23 trains.out ../tests-ready/23.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 24' 
rm -f trains.out 
rm -f trains.in 
cp ../tests-ready/24 trains.in 
./trains_pk_wrong_int   || { echo "Test 24: './trains_pk_wrong_int ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/24 trains.out ../tests-ready/24.a  || { echo "Test 24: './check ../tests-ready/24 trains.out ../tests-ready/24.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Problem checked.
' 
cd .. 
