@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Cleaning ./e_trains (id trains) 
echo =================================== 
IF EXIST work rmdir /q /s work 
IF EXIST tests-ready rmdir /q /s tests-ready 
IF EXIST statement-ready rmdir /q /s statement-ready 
echo Problem successfully cleaned!
 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
