@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Making examples for statements for  . (id trains) 
echo =================================== 
echo Building examples 
IF EXIST work rmdir /q /s work 
IF EXIST statement\examples rmdir /q /s statement\examples 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_st.d 


copy 01.st.hand _001.in >nul 


copy 02.st.hand _002.in >nul 


rem (End of translated text) 

echo Compiling solution, validator and checker... 
g++ -I..\..\..\res\testlib -O2 ..\trains_at.cpp -o trains_at.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\trains_at.cpp -o trains_at.exe' returned non-zero exit code!
  goto error
)
g++ -I..\..\..\res\testlib -O2 ..\validate.cpp -o validate.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\validate.cpp -o validate.exe' returned non-zero exit code!
  goto error
)
g++ -I..\..\..\res\testlib -O2 ..\check.cpp -o check.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\check.cpp -o check.exe' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy _001.in trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 1: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out _001.ans >nul 
validate _001.in _001.ans 
IF errorlevel 1 (
  echo Test 1: 'validate _001.in _001.ans' returned non-zero exit code!
  goto error
)
check _001.in trains.out _001.ans 
IF errorlevel 1 (
  echo Test 1: 'check _001.in trains.out _001.ans' returned non-zero exit code!
  goto error
)

echo Test 2 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy _002.in trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 2: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out _002.ans >nul 
validate _002.in _002.ans 
IF errorlevel 1 (
  echo Test 2: 'validate _002.in _002.ans' returned non-zero exit code!
  goto error
)
check _002.in trains.out _002.ans 
IF errorlevel 1 (
  echo Test 2: 'check _002.in trains.out _002.ans' returned non-zero exit code!
  goto error
)

echo Copying tests to statement/examples 
mkdir ..\statement\examples 
echo Test 1 
copy _001.in ..\statement\examples\_001.in >nul 
copy _001.ans ..\statement\examples\_001.ans >nul 
echo Test 2 
copy _002.in ..\statement\examples\_002.in >nul 
copy _002.ans ..\statement\examples\_002.ans >nul 
echo Problem built. 
cd .. 
echo \FilesWithExample{examples/_001.in}{examples/_001.ans}\FilesWithExample{examples/_002.in}{examples/_002.ans}%%  >statement/_examples.tex
echo Examples created. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
