#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

echo '===================================' 
echo 'Making examples for statements for  ./e_trains (id trains)' 
echo '===================================' 
echo 'Building examples' 
rm -rf ./work 
rm -rf ./statement/examples 
mkdir work 
cp tests/* work/ 
cd work 

echo 'Running test generation script(s)...' 
# Next text has been translated from file(s) do_st.d


cp 01.st.hand _001.in 


cp 02.st.hand _002.in 


# (End of translated text)

echo 'Compiling solution, validator and checker...' 
g++ -I../../../res/testlib -O2 ../trains_at.cpp -o trains_at  || { echo "'g++ -I../../../res/testlib -O2 ../trains_at.cpp -o trains_at' returned non-zero exit code!" ; exit 1; }
g++ -I../../../res/testlib -O2 ../validate.cpp -o validate  || { echo "'g++ -I../../../res/testlib -O2 ../validate.cpp -o validate' returned non-zero exit code!" ; exit 1; }
g++ -I../../../res/testlib -O2 ../check.cpp -o check  || { echo "'g++ -I../../../res/testlib -O2 ../check.cpp -o check' returned non-zero exit code!" ; exit 1; }

echo 'Building answer files, validating and checking them...' 

echo 'Test 1' 
rm -f trains.out 
rm -f trains.in 
cp _001.in trains.in 
./trains_at   || { echo "Test 1: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out _001.ans 
./validate _001.in _001.ans  || { echo "Test 1: './validate _001.in _001.ans' returned non-zero exit code!" ; exit 1; }
./check _001.in trains.out _001.ans  || { echo "Test 1: './check _001.in trains.out _001.ans' returned non-zero exit code!" ; exit 1; }

echo 'Test 2' 
rm -f trains.out 
rm -f trains.in 
cp _002.in trains.in 
./trains_at   || { echo "Test 2: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out _002.ans 
./validate _002.in _002.ans  || { echo "Test 2: './validate _002.in _002.ans' returned non-zero exit code!" ; exit 1; }
./check _002.in trains.out _002.ans  || { echo "Test 2: './check _002.in trains.out _002.ans' returned non-zero exit code!" ; exit 1; }

echo 'Copying tests to statement/examples' 
mkdir ../statement/examples 
echo 'Test 1' 
cp _001.in ../statement/examples/_001.in 
cp _001.ans ../statement/examples/_001.ans 
echo 'Test 2' 
cp _002.in ../statement/examples/_002.in 
cp _002.ans ../statement/examples/_002.ans 
echo 'Problem built.' 
cd .. 
echo '\FilesWithExample{examples/_001.in}{examples/_001.ans}\FilesWithExample{examples/_002.in}{examples/_002.ans}%'  >statement/_examples.tex
echo 'Examples created.' 
