#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

echo '===================================' 
echo 'Building ./e_trains (id trains)' 
echo '===================================' 
rm -rf ./work 
rm -rf ./tests-ready 
mkdir work 
cp tests/* work/ 
cd work 

echo 'Running test generation script(s)...' 
# Next text has been translated from file(s) do_st.d, do_all.d


cp 01.st.hand 01 


cp 02.st.hand 02 



cp 01.st.hand 03 


cp 02.st.hand 04 



cp 01.hand 05 


cp 02.hand 06 


cp 03.hand 07 


g++ -I../../../res/testlib -O2 gen_random.cpp -o gen_random  || { echo "'g++ -I../../../res/testlib -O2 gen_random.cpp -o gen_random' returned non-zero exit code!" ; exit 1; }

g++ -I../../../res/testlib -O2 gen_cycle.cpp -o gen_cycle  || { echo "'g++ -I../../../res/testlib -O2 gen_cycle.cpp -o gen_cycle' returned non-zero exit code!" ; exit 1; }

./gen_cycle  10 10 1  >08 || { echo "'./gen_cycle  10 10 1' returned non-zero exit code!" ; exit 1; }

./gen_cycle  25 25 1  >09 || { echo "'./gen_cycle  25 25 1' returned non-zero exit code!" ; exit 1; }

./gen_cycle  100 100 1  >10 || { echo "'./gen_cycle  100 100 1' returned non-zero exit code!" ; exit 1; }

./gen_cycle  10 1000 100  >11 || { echo "'./gen_cycle  10 1000 100' returned non-zero exit code!" ; exit 1; }

./gen_cycle  100 1000 100  >12 || { echo "'./gen_cycle  100 1000 100' returned non-zero exit code!" ; exit 1; }

./gen_cycle  1000 1000 100  >13 || { echo "'./gen_cycle  1000 1000 100' returned non-zero exit code!" ; exit 1; }

./gen_random  10 1000 100  >14 || { echo "'./gen_random  10 1000 100' returned non-zero exit code!" ; exit 1; }

./gen_random  100 1000 100  >15 || { echo "'./gen_random  100 1000 100' returned non-zero exit code!" ; exit 1; }

./gen_random  1000 1000 100  >16 || { echo "'./gen_random  1000 1000 100' returned non-zero exit code!" ; exit 1; }

./gen_cycle  100 100000 100000  >17 || { echo "'./gen_cycle  100 100000 100000' returned non-zero exit code!" ; exit 1; }

./gen_cycle  1000 100000 100000  >18 || { echo "'./gen_cycle  1000 100000 100000' returned non-zero exit code!" ; exit 1; }

./gen_cycle  10000 100000 100000 a  >19 || { echo "'./gen_cycle  10000 100000 100000 a' returned non-zero exit code!" ; exit 1; }

./gen_cycle  100000 100000 100000 b  >20 || { echo "'./gen_cycle  100000 100000 100000 b' returned non-zero exit code!" ; exit 1; }

./gen_random  100 100000 100000  >21 || { echo "'./gen_random  100 100000 100000' returned non-zero exit code!" ; exit 1; }

./gen_random  1000 100000 100000  >22 || { echo "'./gen_random  1000 100000 100000' returned non-zero exit code!" ; exit 1; }

./gen_random  10000 100000 100000 a  >23 || { echo "'./gen_random  10000 100000 100000 a' returned non-zero exit code!" ; exit 1; }

./gen_random  100000 100000 100000 b  >24 || { echo "'./gen_random  100000 100000 100000 b' returned non-zero exit code!" ; exit 1; }

fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_max.pas  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_max.pas' returned non-zero exit code!" ; exit 1; }

fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_max_2.pas  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_max_2.pas' returned non-zero exit code!" ; exit 1; }

./gen_max   >25 || { echo "'./gen_max ' returned non-zero exit code!" ; exit 1; }

./gen_max_2   >26 || { echo "'./gen_max_2 ' returned non-zero exit code!" ; exit 1; }

# (End of translated text)

echo 'Compiling solution, validator and checker...' 
g++ -I../../../res/testlib -O2 ../trains_at.cpp -o trains_at  || { echo "'g++ -I../../../res/testlib -O2 ../trains_at.cpp -o trains_at' returned non-zero exit code!" ; exit 1; }
g++ -I../../../res/testlib -O2 ../validate.cpp -o validate  || { echo "'g++ -I../../../res/testlib -O2 ../validate.cpp -o validate' returned non-zero exit code!" ; exit 1; }
g++ -I../../../res/testlib -O2 ../check.cpp -o check  || { echo "'g++ -I../../../res/testlib -O2 ../check.cpp -o check' returned non-zero exit code!" ; exit 1; }

echo 'Building answer files, validating and checking them...' 

echo 'Test 1' 
rm -f trains.out 
rm -f trains.in 
cp 01 trains.in 
./trains_at   || { echo "Test 1: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 01.a 
./validate 01 01.a  || { echo "Test 1: './validate 01 01.a' returned non-zero exit code!" ; exit 1; }
./check 01 trains.out 01.a  || { echo "Test 1: './check 01 trains.out 01.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 2' 
rm -f trains.out 
rm -f trains.in 
cp 02 trains.in 
./trains_at   || { echo "Test 2: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 02.a 
./validate 02 02.a  || { echo "Test 2: './validate 02 02.a' returned non-zero exit code!" ; exit 1; }
./check 02 trains.out 02.a  || { echo "Test 2: './check 02 trains.out 02.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 3' 
rm -f trains.out 
rm -f trains.in 
cp 03 trains.in 
./trains_at   || { echo "Test 3: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 03.a 
./validate 03 03.a  || { echo "Test 3: './validate 03 03.a' returned non-zero exit code!" ; exit 1; }
./check 03 trains.out 03.a  || { echo "Test 3: './check 03 trains.out 03.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 4' 
rm -f trains.out 
rm -f trains.in 
cp 04 trains.in 
./trains_at   || { echo "Test 4: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 04.a 
./validate 04 04.a  || { echo "Test 4: './validate 04 04.a' returned non-zero exit code!" ; exit 1; }
./check 04 trains.out 04.a  || { echo "Test 4: './check 04 trains.out 04.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 5' 
rm -f trains.out 
rm -f trains.in 
cp 05 trains.in 
./trains_at   || { echo "Test 5: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 05.a 
./validate 05 05.a  || { echo "Test 5: './validate 05 05.a' returned non-zero exit code!" ; exit 1; }
./check 05 trains.out 05.a  || { echo "Test 5: './check 05 trains.out 05.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 6' 
rm -f trains.out 
rm -f trains.in 
cp 06 trains.in 
./trains_at   || { echo "Test 6: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 06.a 
./validate 06 06.a  || { echo "Test 6: './validate 06 06.a' returned non-zero exit code!" ; exit 1; }
./check 06 trains.out 06.a  || { echo "Test 6: './check 06 trains.out 06.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 7' 
rm -f trains.out 
rm -f trains.in 
cp 07 trains.in 
./trains_at   || { echo "Test 7: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 07.a 
./validate 07 07.a  || { echo "Test 7: './validate 07 07.a' returned non-zero exit code!" ; exit 1; }
./check 07 trains.out 07.a  || { echo "Test 7: './check 07 trains.out 07.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 8' 
rm -f trains.out 
rm -f trains.in 
cp 08 trains.in 
./trains_at   || { echo "Test 8: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 08.a 
./validate 08 08.a  || { echo "Test 8: './validate 08 08.a' returned non-zero exit code!" ; exit 1; }
./check 08 trains.out 08.a  || { echo "Test 8: './check 08 trains.out 08.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 9' 
rm -f trains.out 
rm -f trains.in 
cp 09 trains.in 
./trains_at   || { echo "Test 9: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 09.a 
./validate 09 09.a  || { echo "Test 9: './validate 09 09.a' returned non-zero exit code!" ; exit 1; }
./check 09 trains.out 09.a  || { echo "Test 9: './check 09 trains.out 09.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 10' 
rm -f trains.out 
rm -f trains.in 
cp 10 trains.in 
./trains_at   || { echo "Test 10: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 10.a 
./validate 10 10.a  || { echo "Test 10: './validate 10 10.a' returned non-zero exit code!" ; exit 1; }
./check 10 trains.out 10.a  || { echo "Test 10: './check 10 trains.out 10.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 11' 
rm -f trains.out 
rm -f trains.in 
cp 11 trains.in 
./trains_at   || { echo "Test 11: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 11.a 
./validate 11 11.a  || { echo "Test 11: './validate 11 11.a' returned non-zero exit code!" ; exit 1; }
./check 11 trains.out 11.a  || { echo "Test 11: './check 11 trains.out 11.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 12' 
rm -f trains.out 
rm -f trains.in 
cp 12 trains.in 
./trains_at   || { echo "Test 12: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 12.a 
./validate 12 12.a  || { echo "Test 12: './validate 12 12.a' returned non-zero exit code!" ; exit 1; }
./check 12 trains.out 12.a  || { echo "Test 12: './check 12 trains.out 12.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 13' 
rm -f trains.out 
rm -f trains.in 
cp 13 trains.in 
./trains_at   || { echo "Test 13: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 13.a 
./validate 13 13.a  || { echo "Test 13: './validate 13 13.a' returned non-zero exit code!" ; exit 1; }
./check 13 trains.out 13.a  || { echo "Test 13: './check 13 trains.out 13.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 14' 
rm -f trains.out 
rm -f trains.in 
cp 14 trains.in 
./trains_at   || { echo "Test 14: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 14.a 
./validate 14 14.a  || { echo "Test 14: './validate 14 14.a' returned non-zero exit code!" ; exit 1; }
./check 14 trains.out 14.a  || { echo "Test 14: './check 14 trains.out 14.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 15' 
rm -f trains.out 
rm -f trains.in 
cp 15 trains.in 
./trains_at   || { echo "Test 15: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 15.a 
./validate 15 15.a  || { echo "Test 15: './validate 15 15.a' returned non-zero exit code!" ; exit 1; }
./check 15 trains.out 15.a  || { echo "Test 15: './check 15 trains.out 15.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 16' 
rm -f trains.out 
rm -f trains.in 
cp 16 trains.in 
./trains_at   || { echo "Test 16: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 16.a 
./validate 16 16.a  || { echo "Test 16: './validate 16 16.a' returned non-zero exit code!" ; exit 1; }
./check 16 trains.out 16.a  || { echo "Test 16: './check 16 trains.out 16.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 17' 
rm -f trains.out 
rm -f trains.in 
cp 17 trains.in 
./trains_at   || { echo "Test 17: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 17.a 
./validate 17 17.a  || { echo "Test 17: './validate 17 17.a' returned non-zero exit code!" ; exit 1; }
./check 17 trains.out 17.a  || { echo "Test 17: './check 17 trains.out 17.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 18' 
rm -f trains.out 
rm -f trains.in 
cp 18 trains.in 
./trains_at   || { echo "Test 18: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 18.a 
./validate 18 18.a  || { echo "Test 18: './validate 18 18.a' returned non-zero exit code!" ; exit 1; }
./check 18 trains.out 18.a  || { echo "Test 18: './check 18 trains.out 18.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 19' 
rm -f trains.out 
rm -f trains.in 
cp 19 trains.in 
./trains_at   || { echo "Test 19: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 19.a 
./validate 19 19.a  || { echo "Test 19: './validate 19 19.a' returned non-zero exit code!" ; exit 1; }
./check 19 trains.out 19.a  || { echo "Test 19: './check 19 trains.out 19.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 20' 
rm -f trains.out 
rm -f trains.in 
cp 20 trains.in 
./trains_at   || { echo "Test 20: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 20.a 
./validate 20 20.a  || { echo "Test 20: './validate 20 20.a' returned non-zero exit code!" ; exit 1; }
./check 20 trains.out 20.a  || { echo "Test 20: './check 20 trains.out 20.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 21' 
rm -f trains.out 
rm -f trains.in 
cp 21 trains.in 
./trains_at   || { echo "Test 21: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 21.a 
./validate 21 21.a  || { echo "Test 21: './validate 21 21.a' returned non-zero exit code!" ; exit 1; }
./check 21 trains.out 21.a  || { echo "Test 21: './check 21 trains.out 21.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 22' 
rm -f trains.out 
rm -f trains.in 
cp 22 trains.in 
./trains_at   || { echo "Test 22: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 22.a 
./validate 22 22.a  || { echo "Test 22: './validate 22 22.a' returned non-zero exit code!" ; exit 1; }
./check 22 trains.out 22.a  || { echo "Test 22: './check 22 trains.out 22.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 23' 
rm -f trains.out 
rm -f trains.in 
cp 23 trains.in 
./trains_at   || { echo "Test 23: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 23.a 
./validate 23 23.a  || { echo "Test 23: './validate 23 23.a' returned non-zero exit code!" ; exit 1; }
./check 23 trains.out 23.a  || { echo "Test 23: './check 23 trains.out 23.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 24' 
rm -f trains.out 
rm -f trains.in 
cp 24 trains.in 
./trains_at   || { echo "Test 24: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 24.a 
./validate 24 24.a  || { echo "Test 24: './validate 24 24.a' returned non-zero exit code!" ; exit 1; }
./check 24 trains.out 24.a  || { echo "Test 24: './check 24 trains.out 24.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 25' 
rm -f trains.out 
rm -f trains.in 
cp 25 trains.in 
./trains_at   || { echo "Test 25: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 25.a 
./validate 25 25.a  || { echo "Test 25: './validate 25 25.a' returned non-zero exit code!" ; exit 1; }
./check 25 trains.out 25.a  || { echo "Test 25: './check 25 trains.out 25.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 26' 
rm -f trains.out 
rm -f trains.in 
cp 26 trains.in 
./trains_at   || { echo "Test 26: './trains_at ' returned non-zero exit code!" ; exit 1; }
cp trains.out 26.a 
./validate 26 26.a  || { echo "Test 26: './validate 26 26.a' returned non-zero exit code!" ; exit 1; }
./check 26 trains.out 26.a  || { echo "Test 26: './check 26 trains.out 26.a' returned non-zero exit code!" ; exit 1; }

echo 'Copying tests to tests-ready' 
mkdir ../tests-ready 
echo 'Test 1' 
cp 01 ../tests-ready/01 
cp 01.a ../tests-ready/01.a 
echo 'Test 2' 
cp 02 ../tests-ready/02 
cp 02.a ../tests-ready/02.a 
echo 'Test 3' 
cp 03 ../tests-ready/03 
cp 03.a ../tests-ready/03.a 
echo 'Test 4' 
cp 04 ../tests-ready/04 
cp 04.a ../tests-ready/04.a 
echo 'Test 5' 
cp 05 ../tests-ready/05 
cp 05.a ../tests-ready/05.a 
echo 'Test 6' 
cp 06 ../tests-ready/06 
cp 06.a ../tests-ready/06.a 
echo 'Test 7' 
cp 07 ../tests-ready/07 
cp 07.a ../tests-ready/07.a 
echo 'Test 8' 
cp 08 ../tests-ready/08 
cp 08.a ../tests-ready/08.a 
echo 'Test 9' 
cp 09 ../tests-ready/09 
cp 09.a ../tests-ready/09.a 
echo 'Test 10' 
cp 10 ../tests-ready/10 
cp 10.a ../tests-ready/10.a 
echo 'Test 11' 
cp 11 ../tests-ready/11 
cp 11.a ../tests-ready/11.a 
echo 'Test 12' 
cp 12 ../tests-ready/12 
cp 12.a ../tests-ready/12.a 
echo 'Test 13' 
cp 13 ../tests-ready/13 
cp 13.a ../tests-ready/13.a 
echo 'Test 14' 
cp 14 ../tests-ready/14 
cp 14.a ../tests-ready/14.a 
echo 'Test 15' 
cp 15 ../tests-ready/15 
cp 15.a ../tests-ready/15.a 
echo 'Test 16' 
cp 16 ../tests-ready/16 
cp 16.a ../tests-ready/16.a 
echo 'Test 17' 
cp 17 ../tests-ready/17 
cp 17.a ../tests-ready/17.a 
echo 'Test 18' 
cp 18 ../tests-ready/18 
cp 18.a ../tests-ready/18.a 
echo 'Test 19' 
cp 19 ../tests-ready/19 
cp 19.a ../tests-ready/19.a 
echo 'Test 20' 
cp 20 ../tests-ready/20 
cp 20.a ../tests-ready/20.a 
echo 'Test 21' 
cp 21 ../tests-ready/21 
cp 21.a ../tests-ready/21.a 
echo 'Test 22' 
cp 22 ../tests-ready/22 
cp 22.a ../tests-ready/22.a 
echo 'Test 23' 
cp 23 ../tests-ready/23 
cp 23.a ../tests-ready/23.a 
echo 'Test 24' 
cp 24 ../tests-ready/24 
cp 24.a ../tests-ready/24.a 
echo 'Test 25' 
cp 25 ../tests-ready/25 
cp 25.a ../tests-ready/25.a 
echo 'Test 26' 
cp 26 ../tests-ready/26 
cp 26.a ../tests-ready/26.a 
echo 'Problem built.' 
cd .. 
