@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Building ./e_trains (id trains) 
echo =================================== 
IF EXIST work rmdir /q /s work 
IF EXIST tests-ready rmdir /q /s tests-ready 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_all.d 


copy 01.st.hand 01 >nul 


copy 02.st.hand 02 >nul 



copy 01.hand 03 >nul 


copy 02.hand 04 >nul 


copy 03.hand 05 >nul 


g++ -I..\..\..\res\testlib -O2 gen_random.cpp -o gen_random.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_random.cpp -o gen_random.exe' returned non-zero exit code!
  goto error
)

g++ -I..\..\..\res\testlib -O2 gen_cycle.cpp -o gen_cycle.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_cycle.cpp -o gen_cycle.exe' returned non-zero exit code!
  goto error
)

gen_cycle  10 10 1  >06
IF errorlevel 1 (
  echo 'gen_cycle  10 10 1' returned non-zero exit code!
  goto error
)

gen_cycle  25 25 1  >07
IF errorlevel 1 (
  echo 'gen_cycle  25 25 1' returned non-zero exit code!
  goto error
)

gen_cycle  100 100 1  >08
IF errorlevel 1 (
  echo 'gen_cycle  100 100 1' returned non-zero exit code!
  goto error
)

gen_cycle  10 1000 100  >09
IF errorlevel 1 (
  echo 'gen_cycle  10 1000 100' returned non-zero exit code!
  goto error
)

gen_cycle  100 1000 100  >10
IF errorlevel 1 (
  echo 'gen_cycle  100 1000 100' returned non-zero exit code!
  goto error
)

gen_cycle  1000 1000 100  >11
IF errorlevel 1 (
  echo 'gen_cycle  1000 1000 100' returned non-zero exit code!
  goto error
)

gen_random  10 1000 100  >12
IF errorlevel 1 (
  echo 'gen_random  10 1000 100' returned non-zero exit code!
  goto error
)

gen_random  100 1000 100  >13
IF errorlevel 1 (
  echo 'gen_random  100 1000 100' returned non-zero exit code!
  goto error
)

gen_random  1000 1000 100  >14
IF errorlevel 1 (
  echo 'gen_random  1000 1000 100' returned non-zero exit code!
  goto error
)

gen_cycle  100 100000 100000  >15
IF errorlevel 1 (
  echo 'gen_cycle  100 100000 100000' returned non-zero exit code!
  goto error
)

gen_cycle  1000 100000 100000  >16
IF errorlevel 1 (
  echo 'gen_cycle  1000 100000 100000' returned non-zero exit code!
  goto error
)

gen_cycle  10000 100000 100000 a  >17
IF errorlevel 1 (
  echo 'gen_cycle  10000 100000 100000 a' returned non-zero exit code!
  goto error
)

gen_cycle  100000 100000 100000 b  >18
IF errorlevel 1 (
  echo 'gen_cycle  100000 100000 100000 b' returned non-zero exit code!
  goto error
)

gen_random  100 100000 100000  >19
IF errorlevel 1 (
  echo 'gen_random  100 100000 100000' returned non-zero exit code!
  goto error
)

gen_random  1000 100000 100000  >20
IF errorlevel 1 (
  echo 'gen_random  1000 100000 100000' returned non-zero exit code!
  goto error
)

gen_random  10000 100000 100000 a  >21
IF errorlevel 1 (
  echo 'gen_random  10000 100000 100000 a' returned non-zero exit code!
  goto error
)

gen_random  100000 100000 100000 b  >22
IF errorlevel 1 (
  echo 'gen_random  100000 100000 100000 b' returned non-zero exit code!
  goto error
)

fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_max.pas 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_max.pas' returned non-zero exit code!
  goto error
)

fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_max_2.pas 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_max_2.pas' returned non-zero exit code!
  goto error
)

gen_max   >23
IF errorlevel 1 (
  echo 'gen_max ' returned non-zero exit code!
  goto error
)

gen_max_2   >24
IF errorlevel 1 (
  echo 'gen_max_2 ' returned non-zero exit code!
  goto error
)

rem (End of translated text) 

echo Compiling solution, validator and checker... 
g++ -I..\..\..\res\testlib -O2 ..\trains_at.cpp -o trains_at.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\trains_at.cpp -o trains_at.exe' returned non-zero exit code!
  goto error
)
g++ -I..\..\..\res\testlib -O2 ..\validate.cpp -o validate.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\validate.cpp -o validate.exe' returned non-zero exit code!
  goto error
)
g++ -I..\..\..\res\testlib -O2 ..\check.cpp -o check.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\check.cpp -o check.exe' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 01 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 1: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 01.a >nul 
validate 01 01.a 
IF errorlevel 1 (
  echo Test 1: 'validate 01 01.a' returned non-zero exit code!
  goto error
)
check 01 trains.out 01.a 
IF errorlevel 1 (
  echo Test 1: 'check 01 trains.out 01.a' returned non-zero exit code!
  goto error
)

echo Test 2 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 02 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 2: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 02.a >nul 
validate 02 02.a 
IF errorlevel 1 (
  echo Test 2: 'validate 02 02.a' returned non-zero exit code!
  goto error
)
check 02 trains.out 02.a 
IF errorlevel 1 (
  echo Test 2: 'check 02 trains.out 02.a' returned non-zero exit code!
  goto error
)

echo Test 3 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 03 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 3: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 03.a >nul 
validate 03 03.a 
IF errorlevel 1 (
  echo Test 3: 'validate 03 03.a' returned non-zero exit code!
  goto error
)
check 03 trains.out 03.a 
IF errorlevel 1 (
  echo Test 3: 'check 03 trains.out 03.a' returned non-zero exit code!
  goto error
)

echo Test 4 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 04 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 4: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 04.a >nul 
validate 04 04.a 
IF errorlevel 1 (
  echo Test 4: 'validate 04 04.a' returned non-zero exit code!
  goto error
)
check 04 trains.out 04.a 
IF errorlevel 1 (
  echo Test 4: 'check 04 trains.out 04.a' returned non-zero exit code!
  goto error
)

echo Test 5 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 05 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 5: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 05.a >nul 
validate 05 05.a 
IF errorlevel 1 (
  echo Test 5: 'validate 05 05.a' returned non-zero exit code!
  goto error
)
check 05 trains.out 05.a 
IF errorlevel 1 (
  echo Test 5: 'check 05 trains.out 05.a' returned non-zero exit code!
  goto error
)

echo Test 6 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 06 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 6: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 06.a >nul 
validate 06 06.a 
IF errorlevel 1 (
  echo Test 6: 'validate 06 06.a' returned non-zero exit code!
  goto error
)
check 06 trains.out 06.a 
IF errorlevel 1 (
  echo Test 6: 'check 06 trains.out 06.a' returned non-zero exit code!
  goto error
)

echo Test 7 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 07 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 7: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 07.a >nul 
validate 07 07.a 
IF errorlevel 1 (
  echo Test 7: 'validate 07 07.a' returned non-zero exit code!
  goto error
)
check 07 trains.out 07.a 
IF errorlevel 1 (
  echo Test 7: 'check 07 trains.out 07.a' returned non-zero exit code!
  goto error
)

echo Test 8 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 08 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 8: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 08.a >nul 
validate 08 08.a 
IF errorlevel 1 (
  echo Test 8: 'validate 08 08.a' returned non-zero exit code!
  goto error
)
check 08 trains.out 08.a 
IF errorlevel 1 (
  echo Test 8: 'check 08 trains.out 08.a' returned non-zero exit code!
  goto error
)

echo Test 9 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 09 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 9: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 09.a >nul 
validate 09 09.a 
IF errorlevel 1 (
  echo Test 9: 'validate 09 09.a' returned non-zero exit code!
  goto error
)
check 09 trains.out 09.a 
IF errorlevel 1 (
  echo Test 9: 'check 09 trains.out 09.a' returned non-zero exit code!
  goto error
)

echo Test 10 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 10 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 10: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 10.a >nul 
validate 10 10.a 
IF errorlevel 1 (
  echo Test 10: 'validate 10 10.a' returned non-zero exit code!
  goto error
)
check 10 trains.out 10.a 
IF errorlevel 1 (
  echo Test 10: 'check 10 trains.out 10.a' returned non-zero exit code!
  goto error
)

echo Test 11 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 11 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 11: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 11.a >nul 
validate 11 11.a 
IF errorlevel 1 (
  echo Test 11: 'validate 11 11.a' returned non-zero exit code!
  goto error
)
check 11 trains.out 11.a 
IF errorlevel 1 (
  echo Test 11: 'check 11 trains.out 11.a' returned non-zero exit code!
  goto error
)

echo Test 12 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 12 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 12: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 12.a >nul 
validate 12 12.a 
IF errorlevel 1 (
  echo Test 12: 'validate 12 12.a' returned non-zero exit code!
  goto error
)
check 12 trains.out 12.a 
IF errorlevel 1 (
  echo Test 12: 'check 12 trains.out 12.a' returned non-zero exit code!
  goto error
)

echo Test 13 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 13 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 13: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 13.a >nul 
validate 13 13.a 
IF errorlevel 1 (
  echo Test 13: 'validate 13 13.a' returned non-zero exit code!
  goto error
)
check 13 trains.out 13.a 
IF errorlevel 1 (
  echo Test 13: 'check 13 trains.out 13.a' returned non-zero exit code!
  goto error
)

echo Test 14 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 14 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 14: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 14.a >nul 
validate 14 14.a 
IF errorlevel 1 (
  echo Test 14: 'validate 14 14.a' returned non-zero exit code!
  goto error
)
check 14 trains.out 14.a 
IF errorlevel 1 (
  echo Test 14: 'check 14 trains.out 14.a' returned non-zero exit code!
  goto error
)

echo Test 15 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 15 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 15: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 15.a >nul 
validate 15 15.a 
IF errorlevel 1 (
  echo Test 15: 'validate 15 15.a' returned non-zero exit code!
  goto error
)
check 15 trains.out 15.a 
IF errorlevel 1 (
  echo Test 15: 'check 15 trains.out 15.a' returned non-zero exit code!
  goto error
)

echo Test 16 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 16 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 16: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 16.a >nul 
validate 16 16.a 
IF errorlevel 1 (
  echo Test 16: 'validate 16 16.a' returned non-zero exit code!
  goto error
)
check 16 trains.out 16.a 
IF errorlevel 1 (
  echo Test 16: 'check 16 trains.out 16.a' returned non-zero exit code!
  goto error
)

echo Test 17 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 17 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 17: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 17.a >nul 
validate 17 17.a 
IF errorlevel 1 (
  echo Test 17: 'validate 17 17.a' returned non-zero exit code!
  goto error
)
check 17 trains.out 17.a 
IF errorlevel 1 (
  echo Test 17: 'check 17 trains.out 17.a' returned non-zero exit code!
  goto error
)

echo Test 18 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 18 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 18: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 18.a >nul 
validate 18 18.a 
IF errorlevel 1 (
  echo Test 18: 'validate 18 18.a' returned non-zero exit code!
  goto error
)
check 18 trains.out 18.a 
IF errorlevel 1 (
  echo Test 18: 'check 18 trains.out 18.a' returned non-zero exit code!
  goto error
)

echo Test 19 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 19 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 19: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 19.a >nul 
validate 19 19.a 
IF errorlevel 1 (
  echo Test 19: 'validate 19 19.a' returned non-zero exit code!
  goto error
)
check 19 trains.out 19.a 
IF errorlevel 1 (
  echo Test 19: 'check 19 trains.out 19.a' returned non-zero exit code!
  goto error
)

echo Test 20 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 20 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 20: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 20.a >nul 
validate 20 20.a 
IF errorlevel 1 (
  echo Test 20: 'validate 20 20.a' returned non-zero exit code!
  goto error
)
check 20 trains.out 20.a 
IF errorlevel 1 (
  echo Test 20: 'check 20 trains.out 20.a' returned non-zero exit code!
  goto error
)

echo Test 21 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 21 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 21: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 21.a >nul 
validate 21 21.a 
IF errorlevel 1 (
  echo Test 21: 'validate 21 21.a' returned non-zero exit code!
  goto error
)
check 21 trains.out 21.a 
IF errorlevel 1 (
  echo Test 21: 'check 21 trains.out 21.a' returned non-zero exit code!
  goto error
)

echo Test 22 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 22 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 22: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 22.a >nul 
validate 22 22.a 
IF errorlevel 1 (
  echo Test 22: 'validate 22 22.a' returned non-zero exit code!
  goto error
)
check 22 trains.out 22.a 
IF errorlevel 1 (
  echo Test 22: 'check 22 trains.out 22.a' returned non-zero exit code!
  goto error
)

echo Test 23 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 23 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 23: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 23.a >nul 
validate 23 23.a 
IF errorlevel 1 (
  echo Test 23: 'validate 23 23.a' returned non-zero exit code!
  goto error
)
check 23 trains.out 23.a 
IF errorlevel 1 (
  echo Test 23: 'check 23 trains.out 23.a' returned non-zero exit code!
  goto error
)

echo Test 24 
IF EXIST trains.out del trains.out >nul  
IF EXIST trains.in del trains.in >nul  
copy 24 trains.in >nul 
trains_at  
IF errorlevel 1 (
  echo Test 24: 'trains_at ' returned non-zero exit code!
  goto error
)
copy trains.out 24.a >nul 
validate 24 24.a 
IF errorlevel 1 (
  echo Test 24: 'validate 24 24.a' returned non-zero exit code!
  goto error
)
check 24 trains.out 24.a 
IF errorlevel 1 (
  echo Test 24: 'check 24 trains.out 24.a' returned non-zero exit code!
  goto error
)

echo Copying tests to tests-ready 
mkdir ..\tests-ready 
echo Test 1 
copy 01 ..\tests-ready\01 >nul 
copy 01.a ..\tests-ready\01.a >nul 
echo Test 2 
copy 02 ..\tests-ready\02 >nul 
copy 02.a ..\tests-ready\02.a >nul 
echo Test 3 
copy 03 ..\tests-ready\03 >nul 
copy 03.a ..\tests-ready\03.a >nul 
echo Test 4 
copy 04 ..\tests-ready\04 >nul 
copy 04.a ..\tests-ready\04.a >nul 
echo Test 5 
copy 05 ..\tests-ready\05 >nul 
copy 05.a ..\tests-ready\05.a >nul 
echo Test 6 
copy 06 ..\tests-ready\06 >nul 
copy 06.a ..\tests-ready\06.a >nul 
echo Test 7 
copy 07 ..\tests-ready\07 >nul 
copy 07.a ..\tests-ready\07.a >nul 
echo Test 8 
copy 08 ..\tests-ready\08 >nul 
copy 08.a ..\tests-ready\08.a >nul 
echo Test 9 
copy 09 ..\tests-ready\09 >nul 
copy 09.a ..\tests-ready\09.a >nul 
echo Test 10 
copy 10 ..\tests-ready\10 >nul 
copy 10.a ..\tests-ready\10.a >nul 
echo Test 11 
copy 11 ..\tests-ready\11 >nul 
copy 11.a ..\tests-ready\11.a >nul 
echo Test 12 
copy 12 ..\tests-ready\12 >nul 
copy 12.a ..\tests-ready\12.a >nul 
echo Test 13 
copy 13 ..\tests-ready\13 >nul 
copy 13.a ..\tests-ready\13.a >nul 
echo Test 14 
copy 14 ..\tests-ready\14 >nul 
copy 14.a ..\tests-ready\14.a >nul 
echo Test 15 
copy 15 ..\tests-ready\15 >nul 
copy 15.a ..\tests-ready\15.a >nul 
echo Test 16 
copy 16 ..\tests-ready\16 >nul 
copy 16.a ..\tests-ready\16.a >nul 
echo Test 17 
copy 17 ..\tests-ready\17 >nul 
copy 17.a ..\tests-ready\17.a >nul 
echo Test 18 
copy 18 ..\tests-ready\18 >nul 
copy 18.a ..\tests-ready\18.a >nul 
echo Test 19 
copy 19 ..\tests-ready\19 >nul 
copy 19.a ..\tests-ready\19.a >nul 
echo Test 20 
copy 20 ..\tests-ready\20 >nul 
copy 20.a ..\tests-ready\20.a >nul 
echo Test 21 
copy 21 ..\tests-ready\21 >nul 
copy 21.a ..\tests-ready\21.a >nul 
echo Test 22 
copy 22 ..\tests-ready\22 >nul 
copy 22.a ..\tests-ready\22.a >nul 
echo Test 23 
copy 23 ..\tests-ready\23 >nul 
copy 23.a ..\tests-ready\23.a >nul 
echo Test 24 
copy 24 ..\tests-ready\24 >nul 
copy 24.a ..\tests-ready\24.a >nul 
echo Problem built. 
cd .. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
