@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Making statement for  ./e_trains (id trains) 
echo =================================== 
call _generate_examples.cmd  
IF errorlevel 1 (
  echo '_generate_examples.cmd' returned non-zero exit code!
  goto error
)
IF EXIST work rmdir /q /s work 
IF EXIST statement-ready rmdir /q /s statement-ready 
mkdir work 
cd work 
echo \input{../../_prologue.tex}\import{../statement/}{trains.tex}\end{document}  >trains_full.tex
latex trains_full 
IF errorlevel 1 echo 'latex trains_full' returned non-zero exit code >> ../_daysper.log
latex trains_full 
IF errorlevel 1 echo 'latex trains_full' returned non-zero exit code >> ../_daysper.log
dvips trains_full 
IF errorlevel 1 echo 'dvips trains_full' returned non-zero exit code >> ../_daysper.log
dvipdfmx trains_full 
IF errorlevel 1 echo 'dvipdfmx trains_full' returned non-zero exit code >> ../_daysper.log
mkdir ..\statement-ready 
copy trains_full.ps ..\statement-ready\trains_full.ps >nul 
copy trains_full.pdf ..\statement-ready\trains_full.pdf >nul 
cd .. 
echo Statement created. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
