@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Building ./i_circles (id circles) 
echo =================================== 
IF EXIST work rmdir /q /s work 
IF EXIST tests-ready rmdir /q /s tests-ready 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_all.d 

fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_regular.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_regular.dpr' returned non-zero exit code!
  goto error
)

copy 01.hand 01 >nul 

copy 01.hand.a 01.a >nul 

gen_regular  02 3 105.23 -106.1 137 39 -1 1 
IF errorlevel 1 (
  echo 'gen_regular  02 3 105.23 -106.1 137 39 -1 1' returned non-zero exit code!
  goto error
)

copy 03.hand 03 >nul 

copy 03.hand.a 03.a >nul 

copy 04.hand 04 >nul 

copy 04.hand.a 04.a >nul 


copy 05.hand 05 >nul 

copy 05.hand.a 05.a >nul 


copy 06.hand 06 >nul 

copy 06.hand.a 06.a >nul 


copy 07.hand 07 >nul 

copy 07.hand.a 07.a >nul 


copy 08.hand 08 >nul 

copy 08.hand.a 08.a >nul 


copy 09.hand 09 >nul 

copy 09.hand.a 09.a >nul 


copy 10.hand 10 >nul 

copy 10.hand.a 10.a >nul 



copy 11.hand 11 >nul 

copy 11.hand.a 11.a >nul 


copy 12.hand 12 >nul 

copy 12.hand.a 12.a >nul 


gen_regular  13 5 234 89 29 -90 1 1 
IF errorlevel 1 (
  echo 'gen_regular  13 5 234 89 29 -90 1 1' returned non-zero exit code!
  goto error
)


copy 14.hand 14 >nul 

copy 14.hand.a 14.a >nul 


copy 15.hand 15 >nul 

copy 15.hand.a 15.a >nul 


copy 16.hand 16 >nul 

copy 16.hand.a 16.a >nul 


copy 17.hand 17 >nul 

copy 17.hand.a 17.a >nul 


copy 18.hand 18 >nul 

copy 18.hand.a 18.a >nul 


copy 19.hand 19 >nul 

copy 19.hand.a 19.a >nul 


copy 20.hand 20 >nul 

copy 20.hand.a 20.a >nul 


copy 21.hand 21 >nul 

copy 21.hand.a 21.a >nul 


fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_random.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_random.dpr' returned non-zero exit code!
  goto error
)

fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_line.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res gen_line.dpr' returned non-zero exit code!
  goto error
)

gen_random  22 2355 1000 -10000 10000 -10000 10000 20000 
IF errorlevel 1 (
  echo 'gen_random  22 2355 1000 -10000 10000 -10000 10000 20000' returned non-zero exit code!
  goto error
)

gen_line  23 2359 100 0 -2 1 5 10 
IF errorlevel 1 (
  echo 'gen_line  23 2359 100 0 -2 1 5 10' returned non-zero exit code!
  goto error
)

gen_regular  24 2500 34 57 9900 10 1 2 
IF errorlevel 1 (
  echo 'gen_regular  24 2500 34 57 9900 10 1 2' returned non-zero exit code!
  goto error
)

gen_random  25 1637 9999 -100 100 -100 100 200 
IF errorlevel 1 (
  echo 'gen_random  25 1637 9999 -100 100 -100 100 200' returned non-zero exit code!
  goto error
)

gen_random  26 6736 49999 -10 10 -10 10 20 
IF errorlevel 1 (
  echo 'gen_random  26 6736 49999 -10 10 -10 10 20' returned non-zero exit code!
  goto error
)

gen_random  27 8746 50000 -10000 10000 -10000 10000 20000 
IF errorlevel 1 (
  echo 'gen_random  27 8746 50000 -10000 10000 -10000 10000 20000' returned non-zero exit code!
  goto error
)

gen_random  28 2496 49997 -10000 10000 -10000 10000 10 
IF errorlevel 1 (
  echo 'gen_random  28 2496 49997 -10000 10000 -10000 10000 10' returned non-zero exit code!
  goto error
)

gen_line  29 3148 500 1 2 1 4 100 
IF errorlevel 1 (
  echo 'gen_line  29 3148 500 1 2 1 4 100' returned non-zero exit code!
  goto error
)

gen_regular  30 10000 0 0 10000 0 -1 5 
IF errorlevel 1 (
  echo 'gen_regular  30 10000 0 0 10000 0 -1 5' returned non-zero exit code!
  goto error
)

rem (End of translated text) 

echo Compiling solution, validator and checker... 
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\circles_pk.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\circles_pk.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 01 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 1: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 01 01.a 
IF errorlevel 1 (
  echo Test 1: 'validate 01 01.a' returned non-zero exit code!
  goto error
)
check 01 circles.out 01.a 
IF errorlevel 1 (
  echo Test 1: 'check 01 circles.out 01.a' returned non-zero exit code!
  goto error
)
copy 01.a _tmp.out >nul 
check 01 _tmp.out 01.a 
IF errorlevel 1 (
  echo Test 1: 'check 01 _tmp.out 01.a' returned non-zero exit code!
  goto error
)

echo Test 2 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 02 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 2: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 02.a >nul 
validate 02 02.a 
IF errorlevel 1 (
  echo Test 2: 'validate 02 02.a' returned non-zero exit code!
  goto error
)
check 02 circles.out 02.a 
IF errorlevel 1 (
  echo Test 2: 'check 02 circles.out 02.a' returned non-zero exit code!
  goto error
)

echo Test 3 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 03 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 3: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 03 03.a 
IF errorlevel 1 (
  echo Test 3: 'validate 03 03.a' returned non-zero exit code!
  goto error
)
check 03 circles.out 03.a 
IF errorlevel 1 (
  echo Test 3: 'check 03 circles.out 03.a' returned non-zero exit code!
  goto error
)
copy 03.a _tmp.out >nul 
check 03 _tmp.out 03.a 
IF errorlevel 1 (
  echo Test 3: 'check 03 _tmp.out 03.a' returned non-zero exit code!
  goto error
)

echo Test 4 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 04 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 4: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 04 04.a 
IF errorlevel 1 (
  echo Test 4: 'validate 04 04.a' returned non-zero exit code!
  goto error
)
check 04 circles.out 04.a 
IF errorlevel 1 (
  echo Test 4: 'check 04 circles.out 04.a' returned non-zero exit code!
  goto error
)
copy 04.a _tmp.out >nul 
check 04 _tmp.out 04.a 
IF errorlevel 1 (
  echo Test 4: 'check 04 _tmp.out 04.a' returned non-zero exit code!
  goto error
)

echo Test 5 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 05 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 5: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 05 05.a 
IF errorlevel 1 (
  echo Test 5: 'validate 05 05.a' returned non-zero exit code!
  goto error
)
check 05 circles.out 05.a 
IF errorlevel 1 (
  echo Test 5: 'check 05 circles.out 05.a' returned non-zero exit code!
  goto error
)
copy 05.a _tmp.out >nul 
check 05 _tmp.out 05.a 
IF errorlevel 1 (
  echo Test 5: 'check 05 _tmp.out 05.a' returned non-zero exit code!
  goto error
)

echo Test 6 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 06 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 6: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 06 06.a 
IF errorlevel 1 (
  echo Test 6: 'validate 06 06.a' returned non-zero exit code!
  goto error
)
check 06 circles.out 06.a 
IF errorlevel 1 (
  echo Test 6: 'check 06 circles.out 06.a' returned non-zero exit code!
  goto error
)
copy 06.a _tmp.out >nul 
check 06 _tmp.out 06.a 
IF errorlevel 1 (
  echo Test 6: 'check 06 _tmp.out 06.a' returned non-zero exit code!
  goto error
)

echo Test 7 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 07 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 7: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 07 07.a 
IF errorlevel 1 (
  echo Test 7: 'validate 07 07.a' returned non-zero exit code!
  goto error
)
check 07 circles.out 07.a 
IF errorlevel 1 (
  echo Test 7: 'check 07 circles.out 07.a' returned non-zero exit code!
  goto error
)
copy 07.a _tmp.out >nul 
check 07 _tmp.out 07.a 
IF errorlevel 1 (
  echo Test 7: 'check 07 _tmp.out 07.a' returned non-zero exit code!
  goto error
)

echo Test 8 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 08 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 8: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 08 08.a 
IF errorlevel 1 (
  echo Test 8: 'validate 08 08.a' returned non-zero exit code!
  goto error
)
check 08 circles.out 08.a 
IF errorlevel 1 (
  echo Test 8: 'check 08 circles.out 08.a' returned non-zero exit code!
  goto error
)
copy 08.a _tmp.out >nul 
check 08 _tmp.out 08.a 
IF errorlevel 1 (
  echo Test 8: 'check 08 _tmp.out 08.a' returned non-zero exit code!
  goto error
)

echo Test 9 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 09 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 9: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 09 09.a 
IF errorlevel 1 (
  echo Test 9: 'validate 09 09.a' returned non-zero exit code!
  goto error
)
check 09 circles.out 09.a 
IF errorlevel 1 (
  echo Test 9: 'check 09 circles.out 09.a' returned non-zero exit code!
  goto error
)
copy 09.a _tmp.out >nul 
check 09 _tmp.out 09.a 
IF errorlevel 1 (
  echo Test 9: 'check 09 _tmp.out 09.a' returned non-zero exit code!
  goto error
)

echo Test 10 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 10 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 10: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 10 10.a 
IF errorlevel 1 (
  echo Test 10: 'validate 10 10.a' returned non-zero exit code!
  goto error
)
check 10 circles.out 10.a 
IF errorlevel 1 (
  echo Test 10: 'check 10 circles.out 10.a' returned non-zero exit code!
  goto error
)
copy 10.a _tmp.out >nul 
check 10 _tmp.out 10.a 
IF errorlevel 1 (
  echo Test 10: 'check 10 _tmp.out 10.a' returned non-zero exit code!
  goto error
)

echo Test 11 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 11 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 11: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 11 11.a 
IF errorlevel 1 (
  echo Test 11: 'validate 11 11.a' returned non-zero exit code!
  goto error
)
check 11 circles.out 11.a 
IF errorlevel 1 (
  echo Test 11: 'check 11 circles.out 11.a' returned non-zero exit code!
  goto error
)
copy 11.a _tmp.out >nul 
check 11 _tmp.out 11.a 
IF errorlevel 1 (
  echo Test 11: 'check 11 _tmp.out 11.a' returned non-zero exit code!
  goto error
)

echo Test 12 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 12 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 12: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 12 12.a 
IF errorlevel 1 (
  echo Test 12: 'validate 12 12.a' returned non-zero exit code!
  goto error
)
check 12 circles.out 12.a 
IF errorlevel 1 (
  echo Test 12: 'check 12 circles.out 12.a' returned non-zero exit code!
  goto error
)
copy 12.a _tmp.out >nul 
check 12 _tmp.out 12.a 
IF errorlevel 1 (
  echo Test 12: 'check 12 _tmp.out 12.a' returned non-zero exit code!
  goto error
)

echo Test 13 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 13 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 13: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 13.a >nul 
validate 13 13.a 
IF errorlevel 1 (
  echo Test 13: 'validate 13 13.a' returned non-zero exit code!
  goto error
)
check 13 circles.out 13.a 
IF errorlevel 1 (
  echo Test 13: 'check 13 circles.out 13.a' returned non-zero exit code!
  goto error
)

echo Test 14 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 14 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 14: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 14 14.a 
IF errorlevel 1 (
  echo Test 14: 'validate 14 14.a' returned non-zero exit code!
  goto error
)
check 14 circles.out 14.a 
IF errorlevel 1 (
  echo Test 14: 'check 14 circles.out 14.a' returned non-zero exit code!
  goto error
)
copy 14.a _tmp.out >nul 
check 14 _tmp.out 14.a 
IF errorlevel 1 (
  echo Test 14: 'check 14 _tmp.out 14.a' returned non-zero exit code!
  goto error
)

echo Test 15 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 15 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 15: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 15 15.a 
IF errorlevel 1 (
  echo Test 15: 'validate 15 15.a' returned non-zero exit code!
  goto error
)
check 15 circles.out 15.a 
IF errorlevel 1 (
  echo Test 15: 'check 15 circles.out 15.a' returned non-zero exit code!
  goto error
)
copy 15.a _tmp.out >nul 
check 15 _tmp.out 15.a 
IF errorlevel 1 (
  echo Test 15: 'check 15 _tmp.out 15.a' returned non-zero exit code!
  goto error
)

echo Test 16 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 16 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 16: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 16 16.a 
IF errorlevel 1 (
  echo Test 16: 'validate 16 16.a' returned non-zero exit code!
  goto error
)
check 16 circles.out 16.a 
IF errorlevel 1 (
  echo Test 16: 'check 16 circles.out 16.a' returned non-zero exit code!
  goto error
)
copy 16.a _tmp.out >nul 
check 16 _tmp.out 16.a 
IF errorlevel 1 (
  echo Test 16: 'check 16 _tmp.out 16.a' returned non-zero exit code!
  goto error
)

echo Test 17 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 17 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 17: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 17 17.a 
IF errorlevel 1 (
  echo Test 17: 'validate 17 17.a' returned non-zero exit code!
  goto error
)
check 17 circles.out 17.a 
IF errorlevel 1 (
  echo Test 17: 'check 17 circles.out 17.a' returned non-zero exit code!
  goto error
)
copy 17.a _tmp.out >nul 
check 17 _tmp.out 17.a 
IF errorlevel 1 (
  echo Test 17: 'check 17 _tmp.out 17.a' returned non-zero exit code!
  goto error
)

echo Test 18 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 18 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 18: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 18 18.a 
IF errorlevel 1 (
  echo Test 18: 'validate 18 18.a' returned non-zero exit code!
  goto error
)
check 18 circles.out 18.a 
IF errorlevel 1 (
  echo Test 18: 'check 18 circles.out 18.a' returned non-zero exit code!
  goto error
)
copy 18.a _tmp.out >nul 
check 18 _tmp.out 18.a 
IF errorlevel 1 (
  echo Test 18: 'check 18 _tmp.out 18.a' returned non-zero exit code!
  goto error
)

echo Test 19 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 19 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 19: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 19 19.a 
IF errorlevel 1 (
  echo Test 19: 'validate 19 19.a' returned non-zero exit code!
  goto error
)
check 19 circles.out 19.a 
IF errorlevel 1 (
  echo Test 19: 'check 19 circles.out 19.a' returned non-zero exit code!
  goto error
)
copy 19.a _tmp.out >nul 
check 19 _tmp.out 19.a 
IF errorlevel 1 (
  echo Test 19: 'check 19 _tmp.out 19.a' returned non-zero exit code!
  goto error
)

echo Test 20 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 20 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 20: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 20 20.a 
IF errorlevel 1 (
  echo Test 20: 'validate 20 20.a' returned non-zero exit code!
  goto error
)
check 20 circles.out 20.a 
IF errorlevel 1 (
  echo Test 20: 'check 20 circles.out 20.a' returned non-zero exit code!
  goto error
)
copy 20.a _tmp.out >nul 
check 20 _tmp.out 20.a 
IF errorlevel 1 (
  echo Test 20: 'check 20 _tmp.out 20.a' returned non-zero exit code!
  goto error
)

echo Test 21 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 21 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 21: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate 21 21.a 
IF errorlevel 1 (
  echo Test 21: 'validate 21 21.a' returned non-zero exit code!
  goto error
)
check 21 circles.out 21.a 
IF errorlevel 1 (
  echo Test 21: 'check 21 circles.out 21.a' returned non-zero exit code!
  goto error
)
copy 21.a _tmp.out >nul 
check 21 _tmp.out 21.a 
IF errorlevel 1 (
  echo Test 21: 'check 21 _tmp.out 21.a' returned non-zero exit code!
  goto error
)

echo Test 22 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 22 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 22: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 22.a >nul 
validate 22 22.a 
IF errorlevel 1 (
  echo Test 22: 'validate 22 22.a' returned non-zero exit code!
  goto error
)
check 22 circles.out 22.a 
IF errorlevel 1 (
  echo Test 22: 'check 22 circles.out 22.a' returned non-zero exit code!
  goto error
)

echo Test 23 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 23 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 23: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 23.a >nul 
validate 23 23.a 
IF errorlevel 1 (
  echo Test 23: 'validate 23 23.a' returned non-zero exit code!
  goto error
)
check 23 circles.out 23.a 
IF errorlevel 1 (
  echo Test 23: 'check 23 circles.out 23.a' returned non-zero exit code!
  goto error
)

echo Test 24 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 24 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 24: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 24.a >nul 
validate 24 24.a 
IF errorlevel 1 (
  echo Test 24: 'validate 24 24.a' returned non-zero exit code!
  goto error
)
check 24 circles.out 24.a 
IF errorlevel 1 (
  echo Test 24: 'check 24 circles.out 24.a' returned non-zero exit code!
  goto error
)

echo Test 25 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 25 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 25: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 25.a >nul 
validate 25 25.a 
IF errorlevel 1 (
  echo Test 25: 'validate 25 25.a' returned non-zero exit code!
  goto error
)
check 25 circles.out 25.a 
IF errorlevel 1 (
  echo Test 25: 'check 25 circles.out 25.a' returned non-zero exit code!
  goto error
)

echo Test 26 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 26 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 26: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 26.a >nul 
validate 26 26.a 
IF errorlevel 1 (
  echo Test 26: 'validate 26 26.a' returned non-zero exit code!
  goto error
)
check 26 circles.out 26.a 
IF errorlevel 1 (
  echo Test 26: 'check 26 circles.out 26.a' returned non-zero exit code!
  goto error
)

echo Test 27 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 27 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 27: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 27.a >nul 
validate 27 27.a 
IF errorlevel 1 (
  echo Test 27: 'validate 27 27.a' returned non-zero exit code!
  goto error
)
check 27 circles.out 27.a 
IF errorlevel 1 (
  echo Test 27: 'check 27 circles.out 27.a' returned non-zero exit code!
  goto error
)

echo Test 28 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 28 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 28: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 28.a >nul 
validate 28 28.a 
IF errorlevel 1 (
  echo Test 28: 'validate 28 28.a' returned non-zero exit code!
  goto error
)
check 28 circles.out 28.a 
IF errorlevel 1 (
  echo Test 28: 'check 28 circles.out 28.a' returned non-zero exit code!
  goto error
)

echo Test 29 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 29 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 29: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 29.a >nul 
validate 29 29.a 
IF errorlevel 1 (
  echo Test 29: 'validate 29 29.a' returned non-zero exit code!
  goto error
)
check 29 circles.out 29.a 
IF errorlevel 1 (
  echo Test 29: 'check 29 circles.out 29.a' returned non-zero exit code!
  goto error
)

echo Test 30 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy 30 circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 30: 'circles_pk ' returned non-zero exit code!
  goto error
)
copy circles.out 30.a >nul 
validate 30 30.a 
IF errorlevel 1 (
  echo Test 30: 'validate 30 30.a' returned non-zero exit code!
  goto error
)
check 30 circles.out 30.a 
IF errorlevel 1 (
  echo Test 30: 'check 30 circles.out 30.a' returned non-zero exit code!
  goto error
)

echo Copying tests to tests-ready 
mkdir ..\tests-ready 
echo Test 1 
copy 01 ..\tests-ready\01 >nul 
copy 01.a ..\tests-ready\01.a >nul 
echo Test 2 
copy 02 ..\tests-ready\02 >nul 
copy 02.a ..\tests-ready\02.a >nul 
echo Test 3 
copy 03 ..\tests-ready\03 >nul 
copy 03.a ..\tests-ready\03.a >nul 
echo Test 4 
copy 04 ..\tests-ready\04 >nul 
copy 04.a ..\tests-ready\04.a >nul 
echo Test 5 
copy 05 ..\tests-ready\05 >nul 
copy 05.a ..\tests-ready\05.a >nul 
echo Test 6 
copy 06 ..\tests-ready\06 >nul 
copy 06.a ..\tests-ready\06.a >nul 
echo Test 7 
copy 07 ..\tests-ready\07 >nul 
copy 07.a ..\tests-ready\07.a >nul 
echo Test 8 
copy 08 ..\tests-ready\08 >nul 
copy 08.a ..\tests-ready\08.a >nul 
echo Test 9 
copy 09 ..\tests-ready\09 >nul 
copy 09.a ..\tests-ready\09.a >nul 
echo Test 10 
copy 10 ..\tests-ready\10 >nul 
copy 10.a ..\tests-ready\10.a >nul 
echo Test 11 
copy 11 ..\tests-ready\11 >nul 
copy 11.a ..\tests-ready\11.a >nul 
echo Test 12 
copy 12 ..\tests-ready\12 >nul 
copy 12.a ..\tests-ready\12.a >nul 
echo Test 13 
copy 13 ..\tests-ready\13 >nul 
copy 13.a ..\tests-ready\13.a >nul 
echo Test 14 
copy 14 ..\tests-ready\14 >nul 
copy 14.a ..\tests-ready\14.a >nul 
echo Test 15 
copy 15 ..\tests-ready\15 >nul 
copy 15.a ..\tests-ready\15.a >nul 
echo Test 16 
copy 16 ..\tests-ready\16 >nul 
copy 16.a ..\tests-ready\16.a >nul 
echo Test 17 
copy 17 ..\tests-ready\17 >nul 
copy 17.a ..\tests-ready\17.a >nul 
echo Test 18 
copy 18 ..\tests-ready\18 >nul 
copy 18.a ..\tests-ready\18.a >nul 
echo Test 19 
copy 19 ..\tests-ready\19 >nul 
copy 19.a ..\tests-ready\19.a >nul 
echo Test 20 
copy 20 ..\tests-ready\20 >nul 
copy 20.a ..\tests-ready\20.a >nul 
echo Test 21 
copy 21 ..\tests-ready\21 >nul 
copy 21.a ..\tests-ready\21.a >nul 
echo Test 22 
copy 22 ..\tests-ready\22 >nul 
copy 22.a ..\tests-ready\22.a >nul 
echo Test 23 
copy 23 ..\tests-ready\23 >nul 
copy 23.a ..\tests-ready\23.a >nul 
echo Test 24 
copy 24 ..\tests-ready\24 >nul 
copy 24.a ..\tests-ready\24.a >nul 
echo Test 25 
copy 25 ..\tests-ready\25 >nul 
copy 25.a ..\tests-ready\25.a >nul 
echo Test 26 
copy 26 ..\tests-ready\26 >nul 
copy 26.a ..\tests-ready\26.a >nul 
echo Test 27 
copy 27 ..\tests-ready\27 >nul 
copy 27.a ..\tests-ready\27.a >nul 
echo Test 28 
copy 28 ..\tests-ready\28 >nul 
copy 28.a ..\tests-ready\28.a >nul 
echo Test 29 
copy 29 ..\tests-ready\29 >nul 
copy 29.a ..\tests-ready\29.a >nul 
echo Test 30 
copy 30 ..\tests-ready\30 >nul 
copy 30.a ..\tests-ready\30.a >nul 
echo Problem built. 
cd .. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
