#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

rm -rf ./work 
mkdir work 
cd work 
echo 'Compiling solution and checker' 
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../lottery_model.pas  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../lottery_model.pas' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr' returned non-zero exit code!" ; exit 1; }

echo '' 
echo 'Checking solution' 

echo 'Test 1' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/01 lottery.in 
./lottery_model   || { echo "Test 1: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/01 lottery.out ../tests-ready/01.a  || { echo "Test 1: './check ../tests-ready/01 lottery.out ../tests-ready/01.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 2' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/02 lottery.in 
./lottery_model   || { echo "Test 2: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/02 lottery.out ../tests-ready/02.a  || { echo "Test 2: './check ../tests-ready/02 lottery.out ../tests-ready/02.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 3' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/03 lottery.in 
./lottery_model   || { echo "Test 3: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/03 lottery.out ../tests-ready/03.a  || { echo "Test 3: './check ../tests-ready/03 lottery.out ../tests-ready/03.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 4' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/04 lottery.in 
./lottery_model   || { echo "Test 4: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/04 lottery.out ../tests-ready/04.a  || { echo "Test 4: './check ../tests-ready/04 lottery.out ../tests-ready/04.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 5' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/05 lottery.in 
./lottery_model   || { echo "Test 5: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/05 lottery.out ../tests-ready/05.a  || { echo "Test 5: './check ../tests-ready/05 lottery.out ../tests-ready/05.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 6' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/06 lottery.in 
./lottery_model   || { echo "Test 6: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/06 lottery.out ../tests-ready/06.a  || { echo "Test 6: './check ../tests-ready/06 lottery.out ../tests-ready/06.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 7' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/07 lottery.in 
./lottery_model   || { echo "Test 7: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/07 lottery.out ../tests-ready/07.a  || { echo "Test 7: './check ../tests-ready/07 lottery.out ../tests-ready/07.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 8' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/08 lottery.in 
./lottery_model   || { echo "Test 8: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/08 lottery.out ../tests-ready/08.a  || { echo "Test 8: './check ../tests-ready/08 lottery.out ../tests-ready/08.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 9' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/09 lottery.in 
./lottery_model   || { echo "Test 9: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/09 lottery.out ../tests-ready/09.a  || { echo "Test 9: './check ../tests-ready/09 lottery.out ../tests-ready/09.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 10' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/10 lottery.in 
./lottery_model   || { echo "Test 10: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/10 lottery.out ../tests-ready/10.a  || { echo "Test 10: './check ../tests-ready/10 lottery.out ../tests-ready/10.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 11' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/11 lottery.in 
./lottery_model   || { echo "Test 11: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/11 lottery.out ../tests-ready/11.a  || { echo "Test 11: './check ../tests-ready/11 lottery.out ../tests-ready/11.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 12' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/12 lottery.in 
./lottery_model   || { echo "Test 12: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/12 lottery.out ../tests-ready/12.a  || { echo "Test 12: './check ../tests-ready/12 lottery.out ../tests-ready/12.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 13' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/13 lottery.in 
./lottery_model   || { echo "Test 13: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/13 lottery.out ../tests-ready/13.a  || { echo "Test 13: './check ../tests-ready/13 lottery.out ../tests-ready/13.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 14' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/14 lottery.in 
./lottery_model   || { echo "Test 14: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/14 lottery.out ../tests-ready/14.a  || { echo "Test 14: './check ../tests-ready/14 lottery.out ../tests-ready/14.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 15' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/15 lottery.in 
./lottery_model   || { echo "Test 15: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/15 lottery.out ../tests-ready/15.a  || { echo "Test 15: './check ../tests-ready/15 lottery.out ../tests-ready/15.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 16' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/16 lottery.in 
./lottery_model   || { echo "Test 16: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/16 lottery.out ../tests-ready/16.a  || { echo "Test 16: './check ../tests-ready/16 lottery.out ../tests-ready/16.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 17' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/17 lottery.in 
./lottery_model   || { echo "Test 17: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/17 lottery.out ../tests-ready/17.a  || { echo "Test 17: './check ../tests-ready/17 lottery.out ../tests-ready/17.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 18' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/18 lottery.in 
./lottery_model   || { echo "Test 18: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/18 lottery.out ../tests-ready/18.a  || { echo "Test 18: './check ../tests-ready/18 lottery.out ../tests-ready/18.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 19' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/19 lottery.in 
./lottery_model   || { echo "Test 19: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/19 lottery.out ../tests-ready/19.a  || { echo "Test 19: './check ../tests-ready/19 lottery.out ../tests-ready/19.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 20' 
rm -f lottery.out 
rm -f lottery.in 
cp ../tests-ready/20 lottery.in 
./lottery_model   || { echo "Test 20: './lottery_model ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/20 lottery.out ../tests-ready/20.a  || { echo "Test 20: './check ../tests-ready/20 lottery.out ../tests-ready/20.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Problem checked.
' 
cd .. 
