@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Making statement for  ./g_powersum (id powersum) 
echo =================================== 
call _generate_examples.cmd  
IF errorlevel 1 (
  echo '_generate_examples.cmd' returned non-zero exit code!
  goto error
)
IF EXIST work rmdir /q /s work 
IF EXIST statement-ready rmdir /q /s statement-ready 
mkdir work 
cd work 
echo \input{../../_prologue.tex}\import{../statement/}{powersum.tex}\end{document}  >powersum_full.tex
latex powersum_full 
IF errorlevel 1 echo 'latex powersum_full' returned non-zero exit code >> ../_daysper.log
latex powersum_full 
IF errorlevel 1 echo 'latex powersum_full' returned non-zero exit code >> ../_daysper.log
dvips powersum_full 
IF errorlevel 1 echo 'dvips powersum_full' returned non-zero exit code >> ../_daysper.log
dvipdfmx powersum_full 
IF errorlevel 1 echo 'dvipdfmx powersum_full' returned non-zero exit code >> ../_daysper.log
mkdir ..\statement-ready 
copy powersum_full.ps ..\statement-ready\powersum_full.ps >nul 
copy powersum_full.pdf ..\statement-ready\powersum_full.pdf >nul 
cd .. 
echo Statement created. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
