@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Making examples for statements for  . (id circles) 
echo =================================== 
echo Building examples 
IF EXIST work rmdir /q /s work 
IF EXIST statement\examples rmdir /q /s statement\examples 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_st.d 


copy 01.st.hand _001.in >nul 

copy 01.st.hand.a _001.ans >nul 


copy 02.st.hand _002.in >nul 

copy 02.st.hand.a _002.ans >nul 


rem (End of translated text) 

echo Compiling solution, validator and checker... 
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\circles_pk.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\circles_pk.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy _001.in circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 1: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate _001.in _001.ans 
IF errorlevel 1 (
  echo Test 1: 'validate _001.in _001.ans' returned non-zero exit code!
  goto error
)
check _001.in circles.out _001.ans 
IF errorlevel 1 (
  echo Test 1: 'check _001.in circles.out _001.ans' returned non-zero exit code!
  goto error
)
copy _001.ans _tmp.out >nul 
check _001.in _tmp.out _001.ans 
IF errorlevel 1 (
  echo Test 1: 'check _001.in _tmp.out _001.ans' returned non-zero exit code!
  goto error
)

echo Test 2 
IF EXIST circles.out del circles.out >nul  
IF EXIST circles.in del circles.in >nul  
copy _002.in circles.in >nul 
circles_pk  
IF errorlevel 1 (
  echo Test 2: 'circles_pk ' returned non-zero exit code!
  goto error
)
validate _002.in _002.ans 
IF errorlevel 1 (
  echo Test 2: 'validate _002.in _002.ans' returned non-zero exit code!
  goto error
)
check _002.in circles.out _002.ans 
IF errorlevel 1 (
  echo Test 2: 'check _002.in circles.out _002.ans' returned non-zero exit code!
  goto error
)
copy _002.ans _tmp.out >nul 
check _002.in _tmp.out _002.ans 
IF errorlevel 1 (
  echo Test 2: 'check _002.in _tmp.out _002.ans' returned non-zero exit code!
  goto error
)

echo Copying tests to statement/examples 
mkdir ..\statement\examples 
echo Test 1 
copy _001.in ..\statement\examples\_001.in >nul 
copy _001.ans ..\statement\examples\_001.ans >nul 
echo Test 2 
copy _002.in ..\statement\examples\_002.in >nul 
copy _002.ans ..\statement\examples\_002.ans >nul 
echo Problem built. 
cd .. 
echo \FilesWithExample{examples/_001.in}{examples/_001.ans}\FilesWithExample{examples/_002.in}{examples/_002.ans}%%  >statement/_examples.tex
echo Examples created. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
