#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

echo '===================================' 
echo 'Building ./i_circles (id circles)' 
echo '===================================' 
rm -rf ./work 
rm -rf ./tests-ready 
mkdir work 
cp tests/* work/ 
cd work 

echo 'Running test generation script(s)...' 
# Next text has been translated from file(s) do_st.d, do_all.d


cp 01.st.hand 01 

cp 01.st.hand.a 01.a 


cp 02.st.hand 02 

cp 02.st.hand.a 02.a 


fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_regular.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_regular.dpr' returned non-zero exit code!" ; exit 1; }

cp 01.hand 03 

cp 01.hand.a 03.a 

./gen_regular  04 3 105.23 -106.1 137 39 -1 1  || { echo "'./gen_regular  04 3 105.23 -106.1 137 39 -1 1' returned non-zero exit code!" ; exit 1; }

cp 03.hand 05 

cp 03.hand.a 05.a 

cp 04.hand 06 

cp 04.hand.a 06.a 


cp 05.hand 07 

cp 05.hand.a 07.a 


cp 06.hand 08 

cp 06.hand.a 08.a 


cp 07.hand 09 

cp 07.hand.a 09.a 


cp 08.hand 10 

cp 08.hand.a 10.a 


cp 09.hand 11 

cp 09.hand.a 11.a 


cp 10.hand 12 

cp 10.hand.a 12.a 



cp 11.hand 13 

cp 11.hand.a 13.a 


cp 12.hand 14 

cp 12.hand.a 14.a 


./gen_regular  15 5 234 89 29 -90 1 1  || { echo "'./gen_regular  15 5 234 89 29 -90 1 1' returned non-zero exit code!" ; exit 1; }


cp 14.hand 16 

cp 14.hand.a 16.a 


cp 15.hand 17 

cp 15.hand.a 17.a 


cp 16.hand 18 

cp 16.hand.a 18.a 


cp 17.hand 19 

cp 17.hand.a 19.a 


cp 18.hand 20 

cp 18.hand.a 20.a 


cp 19.hand 21 

cp 19.hand.a 21.a 


cp 20.hand 22 

cp 20.hand.a 22.a 


cp 21.hand 23 

cp 21.hand.a 23.a 


fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_random.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_random.dpr' returned non-zero exit code!" ; exit 1; }

fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_line.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res gen_line.dpr' returned non-zero exit code!" ; exit 1; }

./gen_random  24 2355 1000 -10000 10000 -10000 10000 20000  || { echo "'./gen_random  24 2355 1000 -10000 10000 -10000 10000 20000' returned non-zero exit code!" ; exit 1; }

./gen_line  25 2359 100 0 -2 1 5 10  || { echo "'./gen_line  25 2359 100 0 -2 1 5 10' returned non-zero exit code!" ; exit 1; }

./gen_regular  26 2500 34 57 9900 10 1 2  || { echo "'./gen_regular  26 2500 34 57 9900 10 1 2' returned non-zero exit code!" ; exit 1; }

./gen_random  27 1637 9999 -100 100 -100 100 200  || { echo "'./gen_random  27 1637 9999 -100 100 -100 100 200' returned non-zero exit code!" ; exit 1; }

./gen_random  28 6736 49999 -10 10 -10 10 20  || { echo "'./gen_random  28 6736 49999 -10 10 -10 10 20' returned non-zero exit code!" ; exit 1; }

./gen_random  29 8746 50000 -10000 10000 -10000 10000 20000  || { echo "'./gen_random  29 8746 50000 -10000 10000 -10000 10000 20000' returned non-zero exit code!" ; exit 1; }

./gen_random  30 2496 49997 -10000 10000 -10000 10000 10  || { echo "'./gen_random  30 2496 49997 -10000 10000 -10000 10000 10' returned non-zero exit code!" ; exit 1; }

./gen_line  31 3148 500 1 2 1 4 100  || { echo "'./gen_line  31 3148 500 1 2 1 4 100' returned non-zero exit code!" ; exit 1; }

./gen_regular  32 10000 0 0 10000 0 -1 5  || { echo "'./gen_regular  32 10000 0 0 10000 0 -1 5' returned non-zero exit code!" ; exit 1; }

# (End of translated text)

echo 'Compiling solution, validator and checker...' 
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../circles_pk.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../circles_pk.dpr' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr' returned non-zero exit code!" ; exit 1; }

echo 'Building answer files, validating and checking them...' 

echo 'Test 1' 
rm -f circles.out 
rm -f circles.in 
cp 01 circles.in 
./circles_pk   || { echo "Test 1: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 01 01.a  || { echo "Test 1: './validate 01 01.a' returned non-zero exit code!" ; exit 1; }
./check 01 circles.out 01.a  || { echo "Test 1: './check 01 circles.out 01.a' returned non-zero exit code!" ; exit 1; }
cp 01.a _tmp.out 
./check 01 _tmp.out 01.a  || { echo "Test 1: './check 01 _tmp.out 01.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 2' 
rm -f circles.out 
rm -f circles.in 
cp 02 circles.in 
./circles_pk   || { echo "Test 2: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 02 02.a  || { echo "Test 2: './validate 02 02.a' returned non-zero exit code!" ; exit 1; }
./check 02 circles.out 02.a  || { echo "Test 2: './check 02 circles.out 02.a' returned non-zero exit code!" ; exit 1; }
cp 02.a _tmp.out 
./check 02 _tmp.out 02.a  || { echo "Test 2: './check 02 _tmp.out 02.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 3' 
rm -f circles.out 
rm -f circles.in 
cp 03 circles.in 
./circles_pk   || { echo "Test 3: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 03 03.a  || { echo "Test 3: './validate 03 03.a' returned non-zero exit code!" ; exit 1; }
./check 03 circles.out 03.a  || { echo "Test 3: './check 03 circles.out 03.a' returned non-zero exit code!" ; exit 1; }
cp 03.a _tmp.out 
./check 03 _tmp.out 03.a  || { echo "Test 3: './check 03 _tmp.out 03.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 4' 
rm -f circles.out 
rm -f circles.in 
cp 04 circles.in 
./circles_pk   || { echo "Test 4: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 04.a 
./validate 04 04.a  || { echo "Test 4: './validate 04 04.a' returned non-zero exit code!" ; exit 1; }
./check 04 circles.out 04.a  || { echo "Test 4: './check 04 circles.out 04.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 5' 
rm -f circles.out 
rm -f circles.in 
cp 05 circles.in 
./circles_pk   || { echo "Test 5: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 05 05.a  || { echo "Test 5: './validate 05 05.a' returned non-zero exit code!" ; exit 1; }
./check 05 circles.out 05.a  || { echo "Test 5: './check 05 circles.out 05.a' returned non-zero exit code!" ; exit 1; }
cp 05.a _tmp.out 
./check 05 _tmp.out 05.a  || { echo "Test 5: './check 05 _tmp.out 05.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 6' 
rm -f circles.out 
rm -f circles.in 
cp 06 circles.in 
./circles_pk   || { echo "Test 6: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 06 06.a  || { echo "Test 6: './validate 06 06.a' returned non-zero exit code!" ; exit 1; }
./check 06 circles.out 06.a  || { echo "Test 6: './check 06 circles.out 06.a' returned non-zero exit code!" ; exit 1; }
cp 06.a _tmp.out 
./check 06 _tmp.out 06.a  || { echo "Test 6: './check 06 _tmp.out 06.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 7' 
rm -f circles.out 
rm -f circles.in 
cp 07 circles.in 
./circles_pk   || { echo "Test 7: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 07 07.a  || { echo "Test 7: './validate 07 07.a' returned non-zero exit code!" ; exit 1; }
./check 07 circles.out 07.a  || { echo "Test 7: './check 07 circles.out 07.a' returned non-zero exit code!" ; exit 1; }
cp 07.a _tmp.out 
./check 07 _tmp.out 07.a  || { echo "Test 7: './check 07 _tmp.out 07.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 8' 
rm -f circles.out 
rm -f circles.in 
cp 08 circles.in 
./circles_pk   || { echo "Test 8: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 08 08.a  || { echo "Test 8: './validate 08 08.a' returned non-zero exit code!" ; exit 1; }
./check 08 circles.out 08.a  || { echo "Test 8: './check 08 circles.out 08.a' returned non-zero exit code!" ; exit 1; }
cp 08.a _tmp.out 
./check 08 _tmp.out 08.a  || { echo "Test 8: './check 08 _tmp.out 08.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 9' 
rm -f circles.out 
rm -f circles.in 
cp 09 circles.in 
./circles_pk   || { echo "Test 9: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 09 09.a  || { echo "Test 9: './validate 09 09.a' returned non-zero exit code!" ; exit 1; }
./check 09 circles.out 09.a  || { echo "Test 9: './check 09 circles.out 09.a' returned non-zero exit code!" ; exit 1; }
cp 09.a _tmp.out 
./check 09 _tmp.out 09.a  || { echo "Test 9: './check 09 _tmp.out 09.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 10' 
rm -f circles.out 
rm -f circles.in 
cp 10 circles.in 
./circles_pk   || { echo "Test 10: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 10 10.a  || { echo "Test 10: './validate 10 10.a' returned non-zero exit code!" ; exit 1; }
./check 10 circles.out 10.a  || { echo "Test 10: './check 10 circles.out 10.a' returned non-zero exit code!" ; exit 1; }
cp 10.a _tmp.out 
./check 10 _tmp.out 10.a  || { echo "Test 10: './check 10 _tmp.out 10.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 11' 
rm -f circles.out 
rm -f circles.in 
cp 11 circles.in 
./circles_pk   || { echo "Test 11: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 11 11.a  || { echo "Test 11: './validate 11 11.a' returned non-zero exit code!" ; exit 1; }
./check 11 circles.out 11.a  || { echo "Test 11: './check 11 circles.out 11.a' returned non-zero exit code!" ; exit 1; }
cp 11.a _tmp.out 
./check 11 _tmp.out 11.a  || { echo "Test 11: './check 11 _tmp.out 11.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 12' 
rm -f circles.out 
rm -f circles.in 
cp 12 circles.in 
./circles_pk   || { echo "Test 12: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 12 12.a  || { echo "Test 12: './validate 12 12.a' returned non-zero exit code!" ; exit 1; }
./check 12 circles.out 12.a  || { echo "Test 12: './check 12 circles.out 12.a' returned non-zero exit code!" ; exit 1; }
cp 12.a _tmp.out 
./check 12 _tmp.out 12.a  || { echo "Test 12: './check 12 _tmp.out 12.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 13' 
rm -f circles.out 
rm -f circles.in 
cp 13 circles.in 
./circles_pk   || { echo "Test 13: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 13 13.a  || { echo "Test 13: './validate 13 13.a' returned non-zero exit code!" ; exit 1; }
./check 13 circles.out 13.a  || { echo "Test 13: './check 13 circles.out 13.a' returned non-zero exit code!" ; exit 1; }
cp 13.a _tmp.out 
./check 13 _tmp.out 13.a  || { echo "Test 13: './check 13 _tmp.out 13.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 14' 
rm -f circles.out 
rm -f circles.in 
cp 14 circles.in 
./circles_pk   || { echo "Test 14: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 14 14.a  || { echo "Test 14: './validate 14 14.a' returned non-zero exit code!" ; exit 1; }
./check 14 circles.out 14.a  || { echo "Test 14: './check 14 circles.out 14.a' returned non-zero exit code!" ; exit 1; }
cp 14.a _tmp.out 
./check 14 _tmp.out 14.a  || { echo "Test 14: './check 14 _tmp.out 14.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 15' 
rm -f circles.out 
rm -f circles.in 
cp 15 circles.in 
./circles_pk   || { echo "Test 15: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 15.a 
./validate 15 15.a  || { echo "Test 15: './validate 15 15.a' returned non-zero exit code!" ; exit 1; }
./check 15 circles.out 15.a  || { echo "Test 15: './check 15 circles.out 15.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 16' 
rm -f circles.out 
rm -f circles.in 
cp 16 circles.in 
./circles_pk   || { echo "Test 16: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 16 16.a  || { echo "Test 16: './validate 16 16.a' returned non-zero exit code!" ; exit 1; }
./check 16 circles.out 16.a  || { echo "Test 16: './check 16 circles.out 16.a' returned non-zero exit code!" ; exit 1; }
cp 16.a _tmp.out 
./check 16 _tmp.out 16.a  || { echo "Test 16: './check 16 _tmp.out 16.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 17' 
rm -f circles.out 
rm -f circles.in 
cp 17 circles.in 
./circles_pk   || { echo "Test 17: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 17 17.a  || { echo "Test 17: './validate 17 17.a' returned non-zero exit code!" ; exit 1; }
./check 17 circles.out 17.a  || { echo "Test 17: './check 17 circles.out 17.a' returned non-zero exit code!" ; exit 1; }
cp 17.a _tmp.out 
./check 17 _tmp.out 17.a  || { echo "Test 17: './check 17 _tmp.out 17.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 18' 
rm -f circles.out 
rm -f circles.in 
cp 18 circles.in 
./circles_pk   || { echo "Test 18: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 18 18.a  || { echo "Test 18: './validate 18 18.a' returned non-zero exit code!" ; exit 1; }
./check 18 circles.out 18.a  || { echo "Test 18: './check 18 circles.out 18.a' returned non-zero exit code!" ; exit 1; }
cp 18.a _tmp.out 
./check 18 _tmp.out 18.a  || { echo "Test 18: './check 18 _tmp.out 18.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 19' 
rm -f circles.out 
rm -f circles.in 
cp 19 circles.in 
./circles_pk   || { echo "Test 19: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 19 19.a  || { echo "Test 19: './validate 19 19.a' returned non-zero exit code!" ; exit 1; }
./check 19 circles.out 19.a  || { echo "Test 19: './check 19 circles.out 19.a' returned non-zero exit code!" ; exit 1; }
cp 19.a _tmp.out 
./check 19 _tmp.out 19.a  || { echo "Test 19: './check 19 _tmp.out 19.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 20' 
rm -f circles.out 
rm -f circles.in 
cp 20 circles.in 
./circles_pk   || { echo "Test 20: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 20 20.a  || { echo "Test 20: './validate 20 20.a' returned non-zero exit code!" ; exit 1; }
./check 20 circles.out 20.a  || { echo "Test 20: './check 20 circles.out 20.a' returned non-zero exit code!" ; exit 1; }
cp 20.a _tmp.out 
./check 20 _tmp.out 20.a  || { echo "Test 20: './check 20 _tmp.out 20.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 21' 
rm -f circles.out 
rm -f circles.in 
cp 21 circles.in 
./circles_pk   || { echo "Test 21: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 21 21.a  || { echo "Test 21: './validate 21 21.a' returned non-zero exit code!" ; exit 1; }
./check 21 circles.out 21.a  || { echo "Test 21: './check 21 circles.out 21.a' returned non-zero exit code!" ; exit 1; }
cp 21.a _tmp.out 
./check 21 _tmp.out 21.a  || { echo "Test 21: './check 21 _tmp.out 21.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 22' 
rm -f circles.out 
rm -f circles.in 
cp 22 circles.in 
./circles_pk   || { echo "Test 22: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 22 22.a  || { echo "Test 22: './validate 22 22.a' returned non-zero exit code!" ; exit 1; }
./check 22 circles.out 22.a  || { echo "Test 22: './check 22 circles.out 22.a' returned non-zero exit code!" ; exit 1; }
cp 22.a _tmp.out 
./check 22 _tmp.out 22.a  || { echo "Test 22: './check 22 _tmp.out 22.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 23' 
rm -f circles.out 
rm -f circles.in 
cp 23 circles.in 
./circles_pk   || { echo "Test 23: './circles_pk ' returned non-zero exit code!" ; exit 1; }
./validate 23 23.a  || { echo "Test 23: './validate 23 23.a' returned non-zero exit code!" ; exit 1; }
./check 23 circles.out 23.a  || { echo "Test 23: './check 23 circles.out 23.a' returned non-zero exit code!" ; exit 1; }
cp 23.a _tmp.out 
./check 23 _tmp.out 23.a  || { echo "Test 23: './check 23 _tmp.out 23.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 24' 
rm -f circles.out 
rm -f circles.in 
cp 24 circles.in 
./circles_pk   || { echo "Test 24: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 24.a 
./validate 24 24.a  || { echo "Test 24: './validate 24 24.a' returned non-zero exit code!" ; exit 1; }
./check 24 circles.out 24.a  || { echo "Test 24: './check 24 circles.out 24.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 25' 
rm -f circles.out 
rm -f circles.in 
cp 25 circles.in 
./circles_pk   || { echo "Test 25: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 25.a 
./validate 25 25.a  || { echo "Test 25: './validate 25 25.a' returned non-zero exit code!" ; exit 1; }
./check 25 circles.out 25.a  || { echo "Test 25: './check 25 circles.out 25.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 26' 
rm -f circles.out 
rm -f circles.in 
cp 26 circles.in 
./circles_pk   || { echo "Test 26: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 26.a 
./validate 26 26.a  || { echo "Test 26: './validate 26 26.a' returned non-zero exit code!" ; exit 1; }
./check 26 circles.out 26.a  || { echo "Test 26: './check 26 circles.out 26.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 27' 
rm -f circles.out 
rm -f circles.in 
cp 27 circles.in 
./circles_pk   || { echo "Test 27: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 27.a 
./validate 27 27.a  || { echo "Test 27: './validate 27 27.a' returned non-zero exit code!" ; exit 1; }
./check 27 circles.out 27.a  || { echo "Test 27: './check 27 circles.out 27.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 28' 
rm -f circles.out 
rm -f circles.in 
cp 28 circles.in 
./circles_pk   || { echo "Test 28: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 28.a 
./validate 28 28.a  || { echo "Test 28: './validate 28 28.a' returned non-zero exit code!" ; exit 1; }
./check 28 circles.out 28.a  || { echo "Test 28: './check 28 circles.out 28.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 29' 
rm -f circles.out 
rm -f circles.in 
cp 29 circles.in 
./circles_pk   || { echo "Test 29: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 29.a 
./validate 29 29.a  || { echo "Test 29: './validate 29 29.a' returned non-zero exit code!" ; exit 1; }
./check 29 circles.out 29.a  || { echo "Test 29: './check 29 circles.out 29.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 30' 
rm -f circles.out 
rm -f circles.in 
cp 30 circles.in 
./circles_pk   || { echo "Test 30: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 30.a 
./validate 30 30.a  || { echo "Test 30: './validate 30 30.a' returned non-zero exit code!" ; exit 1; }
./check 30 circles.out 30.a  || { echo "Test 30: './check 30 circles.out 30.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 31' 
rm -f circles.out 
rm -f circles.in 
cp 31 circles.in 
./circles_pk   || { echo "Test 31: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 31.a 
./validate 31 31.a  || { echo "Test 31: './validate 31 31.a' returned non-zero exit code!" ; exit 1; }
./check 31 circles.out 31.a  || { echo "Test 31: './check 31 circles.out 31.a' returned non-zero exit code!" ; exit 1; }

echo 'Test 32' 
rm -f circles.out 
rm -f circles.in 
cp 32 circles.in 
./circles_pk   || { echo "Test 32: './circles_pk ' returned non-zero exit code!" ; exit 1; }
cp circles.out 32.a 
./validate 32 32.a  || { echo "Test 32: './validate 32 32.a' returned non-zero exit code!" ; exit 1; }
./check 32 circles.out 32.a  || { echo "Test 32: './check 32 circles.out 32.a' returned non-zero exit code!" ; exit 1; }

echo 'Copying tests to tests-ready' 
mkdir ../tests-ready 
echo 'Test 1' 
cp 01 ../tests-ready/01 
cp 01.a ../tests-ready/01.a 
echo 'Test 2' 
cp 02 ../tests-ready/02 
cp 02.a ../tests-ready/02.a 
echo 'Test 3' 
cp 03 ../tests-ready/03 
cp 03.a ../tests-ready/03.a 
echo 'Test 4' 
cp 04 ../tests-ready/04 
cp 04.a ../tests-ready/04.a 
echo 'Test 5' 
cp 05 ../tests-ready/05 
cp 05.a ../tests-ready/05.a 
echo 'Test 6' 
cp 06 ../tests-ready/06 
cp 06.a ../tests-ready/06.a 
echo 'Test 7' 
cp 07 ../tests-ready/07 
cp 07.a ../tests-ready/07.a 
echo 'Test 8' 
cp 08 ../tests-ready/08 
cp 08.a ../tests-ready/08.a 
echo 'Test 9' 
cp 09 ../tests-ready/09 
cp 09.a ../tests-ready/09.a 
echo 'Test 10' 
cp 10 ../tests-ready/10 
cp 10.a ../tests-ready/10.a 
echo 'Test 11' 
cp 11 ../tests-ready/11 
cp 11.a ../tests-ready/11.a 
echo 'Test 12' 
cp 12 ../tests-ready/12 
cp 12.a ../tests-ready/12.a 
echo 'Test 13' 
cp 13 ../tests-ready/13 
cp 13.a ../tests-ready/13.a 
echo 'Test 14' 
cp 14 ../tests-ready/14 
cp 14.a ../tests-ready/14.a 
echo 'Test 15' 
cp 15 ../tests-ready/15 
cp 15.a ../tests-ready/15.a 
echo 'Test 16' 
cp 16 ../tests-ready/16 
cp 16.a ../tests-ready/16.a 
echo 'Test 17' 
cp 17 ../tests-ready/17 
cp 17.a ../tests-ready/17.a 
echo 'Test 18' 
cp 18 ../tests-ready/18 
cp 18.a ../tests-ready/18.a 
echo 'Test 19' 
cp 19 ../tests-ready/19 
cp 19.a ../tests-ready/19.a 
echo 'Test 20' 
cp 20 ../tests-ready/20 
cp 20.a ../tests-ready/20.a 
echo 'Test 21' 
cp 21 ../tests-ready/21 
cp 21.a ../tests-ready/21.a 
echo 'Test 22' 
cp 22 ../tests-ready/22 
cp 22.a ../tests-ready/22.a 
echo 'Test 23' 
cp 23 ../tests-ready/23 
cp 23.a ../tests-ready/23.a 
echo 'Test 24' 
cp 24 ../tests-ready/24 
cp 24.a ../tests-ready/24.a 
echo 'Test 25' 
cp 25 ../tests-ready/25 
cp 25.a ../tests-ready/25.a 
echo 'Test 26' 
cp 26 ../tests-ready/26 
cp 26.a ../tests-ready/26.a 
echo 'Test 27' 
cp 27 ../tests-ready/27 
cp 27.a ../tests-ready/27.a 
echo 'Test 28' 
cp 28 ../tests-ready/28 
cp 28.a ../tests-ready/28.a 
echo 'Test 29' 
cp 29 ../tests-ready/29 
cp 29.a ../tests-ready/29.a 
echo 'Test 30' 
cp 30 ../tests-ready/30 
cp 30.a ../tests-ready/30.a 
echo 'Test 31' 
cp 31 ../tests-ready/31 
cp 31.a ../tests-ready/31.a 
echo 'Test 32' 
cp 32 ../tests-ready/32 
cp 32.a ../tests-ready/32.a 
echo 'Problem built.' 
cd .. 
