#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

echo '===================================' 
echo 'Making examples for statements for  ./c_pots (id pots)' 
echo '===================================' 
echo 'Building examples' 
rm -rf ./work 
rm -rf ./statement/examples 
mkdir work 
cp tests/* work/ 
cd work 

echo 'Running test generation script(s)...' 
# Next text has been translated from file(s) do_st.d


cp st01.hand _001.in 

cp st01.a.hand _001.ans 


# (End of translated text)

echo 'Compiling solution, validator and checker...' 
g++ -I../../../res/testlib -O2 ../pots_el.cpp -o pots_el  || { echo "'g++ -I../../../res/testlib -O2 ../pots_el.cpp -o pots_el' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr' returned non-zero exit code!" ; exit 1; }

echo 'Building answer files, validating and checking them...' 

echo 'Test 1' 
rm -f pots.out 
rm -f pots.in 
cp _001.in pots.in 
./pots_el   || { echo "Test 1: './pots_el ' returned non-zero exit code!" ; exit 1; }
./validate _001.in _001.ans  || { echo "Test 1: './validate _001.in _001.ans' returned non-zero exit code!" ; exit 1; }
./check _001.in pots.out _001.ans  || { echo "Test 1: './check _001.in pots.out _001.ans' returned non-zero exit code!" ; exit 1; }
cp _001.ans _tmp.out 
./check _001.in _tmp.out _001.ans  || { echo "Test 1: './check _001.in _tmp.out _001.ans' returned non-zero exit code!" ; exit 1; }

echo 'Copying tests to statement/examples' 
mkdir ../statement/examples 
echo 'Test 1' 
cp _001.in ../statement/examples/_001.in 
cp _001.ans ../statement/examples/_001.ans 
echo 'Problem built.' 
cd .. 
echo '\FilesWithExample{examples/_001.in}{examples/_001.ans}%'  >statement/_examples.tex
echo 'Examples created.' 
