#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

rm -rf ./work 
mkdir work 
cd work 
echo 'Compiling solution and checker' 
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../pots_pk.pas  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../pots_pk.pas' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr' returned non-zero exit code!" ; exit 1; }

echo '' 
echo 'Checking solution' 

echo 'Test 1' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/01 pots.in 
./pots_pk   || { echo "Test 1: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/01 pots.out ../tests-ready/01.a  || { echo "Test 1: './check ../tests-ready/01 pots.out ../tests-ready/01.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 2' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/02 pots.in 
./pots_pk   || { echo "Test 2: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/02 pots.out ../tests-ready/02.a  || { echo "Test 2: './check ../tests-ready/02 pots.out ../tests-ready/02.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 3' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/03 pots.in 
./pots_pk   || { echo "Test 3: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/03 pots.out ../tests-ready/03.a  || { echo "Test 3: './check ../tests-ready/03 pots.out ../tests-ready/03.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 4' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/04 pots.in 
./pots_pk   || { echo "Test 4: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/04 pots.out ../tests-ready/04.a  || { echo "Test 4: './check ../tests-ready/04 pots.out ../tests-ready/04.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 5' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/05 pots.in 
./pots_pk   || { echo "Test 5: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/05 pots.out ../tests-ready/05.a  || { echo "Test 5: './check ../tests-ready/05 pots.out ../tests-ready/05.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 6' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/06 pots.in 
./pots_pk   || { echo "Test 6: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/06 pots.out ../tests-ready/06.a  || { echo "Test 6: './check ../tests-ready/06 pots.out ../tests-ready/06.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 7' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/07 pots.in 
./pots_pk   || { echo "Test 7: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/07 pots.out ../tests-ready/07.a  || { echo "Test 7: './check ../tests-ready/07 pots.out ../tests-ready/07.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 8' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/08 pots.in 
./pots_pk   || { echo "Test 8: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/08 pots.out ../tests-ready/08.a  || { echo "Test 8: './check ../tests-ready/08 pots.out ../tests-ready/08.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 9' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/09 pots.in 
./pots_pk   || { echo "Test 9: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/09 pots.out ../tests-ready/09.a  || { echo "Test 9: './check ../tests-ready/09 pots.out ../tests-ready/09.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 10' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/10 pots.in 
./pots_pk   || { echo "Test 10: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/10 pots.out ../tests-ready/10.a  || { echo "Test 10: './check ../tests-ready/10 pots.out ../tests-ready/10.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 11' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/11 pots.in 
./pots_pk   || { echo "Test 11: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/11 pots.out ../tests-ready/11.a  || { echo "Test 11: './check ../tests-ready/11 pots.out ../tests-ready/11.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 12' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/12 pots.in 
./pots_pk   || { echo "Test 12: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/12 pots.out ../tests-ready/12.a  || { echo "Test 12: './check ../tests-ready/12 pots.out ../tests-ready/12.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 13' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/13 pots.in 
./pots_pk   || { echo "Test 13: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/13 pots.out ../tests-ready/13.a  || { echo "Test 13: './check ../tests-ready/13 pots.out ../tests-ready/13.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 14' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/14 pots.in 
./pots_pk   || { echo "Test 14: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/14 pots.out ../tests-ready/14.a  || { echo "Test 14: './check ../tests-ready/14 pots.out ../tests-ready/14.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 15' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/15 pots.in 
./pots_pk   || { echo "Test 15: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/15 pots.out ../tests-ready/15.a  || { echo "Test 15: './check ../tests-ready/15 pots.out ../tests-ready/15.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 16' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/16 pots.in 
./pots_pk   || { echo "Test 16: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/16 pots.out ../tests-ready/16.a  || { echo "Test 16: './check ../tests-ready/16 pots.out ../tests-ready/16.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 17' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/17 pots.in 
./pots_pk   || { echo "Test 17: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/17 pots.out ../tests-ready/17.a  || { echo "Test 17: './check ../tests-ready/17 pots.out ../tests-ready/17.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 18' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/18 pots.in 
./pots_pk   || { echo "Test 18: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/18 pots.out ../tests-ready/18.a  || { echo "Test 18: './check ../tests-ready/18 pots.out ../tests-ready/18.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 19' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/19 pots.in 
./pots_pk   || { echo "Test 19: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/19 pots.out ../tests-ready/19.a  || { echo "Test 19: './check ../tests-ready/19 pots.out ../tests-ready/19.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 20' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/20 pots.in 
./pots_pk   || { echo "Test 20: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/20 pots.out ../tests-ready/20.a  || { echo "Test 20: './check ../tests-ready/20 pots.out ../tests-ready/20.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 21' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/21 pots.in 
./pots_pk   || { echo "Test 21: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/21 pots.out ../tests-ready/21.a  || { echo "Test 21: './check ../tests-ready/21 pots.out ../tests-ready/21.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 22' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/22 pots.in 
./pots_pk   || { echo "Test 22: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/22 pots.out ../tests-ready/22.a  || { echo "Test 22: './check ../tests-ready/22 pots.out ../tests-ready/22.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 23' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/23 pots.in 
./pots_pk   || { echo "Test 23: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/23 pots.out ../tests-ready/23.a  || { echo "Test 23: './check ../tests-ready/23 pots.out ../tests-ready/23.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 24' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/24 pots.in 
./pots_pk   || { echo "Test 24: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/24 pots.out ../tests-ready/24.a  || { echo "Test 24: './check ../tests-ready/24 pots.out ../tests-ready/24.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 25' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/25 pots.in 
./pots_pk   || { echo "Test 25: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/25 pots.out ../tests-ready/25.a  || { echo "Test 25: './check ../tests-ready/25 pots.out ../tests-ready/25.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 26' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/26 pots.in 
./pots_pk   || { echo "Test 26: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/26 pots.out ../tests-ready/26.a  || { echo "Test 26: './check ../tests-ready/26 pots.out ../tests-ready/26.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 27' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/27 pots.in 
./pots_pk   || { echo "Test 27: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/27 pots.out ../tests-ready/27.a  || { echo "Test 27: './check ../tests-ready/27 pots.out ../tests-ready/27.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 28' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/28 pots.in 
./pots_pk   || { echo "Test 28: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/28 pots.out ../tests-ready/28.a  || { echo "Test 28: './check ../tests-ready/28 pots.out ../tests-ready/28.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 29' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/29 pots.in 
./pots_pk   || { echo "Test 29: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/29 pots.out ../tests-ready/29.a  || { echo "Test 29: './check ../tests-ready/29 pots.out ../tests-ready/29.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Test 30' 
rm -f pots.out 
rm -f pots.in 
cp ../tests-ready/30 pots.in 
./pots_pk   || { echo "Test 30: './pots_pk ' returned non-zero exit code!" >> ../_daysper.log ; }
./check ../tests-ready/30 pots.out ../tests-ready/30.a  || { echo "Test 30: './check ../tests-ready/30 pots.out ../tests-ready/30.a' returned non-zero exit code!" >> ../_daysper.log ; }

echo 'Problem checked.
' 
cd .. 
