@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Making examples for statements for  . (id pots) 
echo =================================== 
echo Building examples 
IF EXIST work rmdir /q /s work 
IF EXIST statement\examples rmdir /q /s statement\examples 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_st.d 


copy st01.hand _001.in >nul 

copy st01.a.hand _001.ans >nul 


rem (End of translated text) 

echo Compiling solution, validator and checker... 
g++ -I..\..\..\res\testlib -O2 ..\pots_el.cpp -o pots_el.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\pots_el.cpp -o pots_el.exe' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy _001.in pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 1: 'pots_el ' returned non-zero exit code!
  goto error
)
validate _001.in _001.ans 
IF errorlevel 1 (
  echo Test 1: 'validate _001.in _001.ans' returned non-zero exit code!
  goto error
)
check _001.in pots.out _001.ans 
IF errorlevel 1 (
  echo Test 1: 'check _001.in pots.out _001.ans' returned non-zero exit code!
  goto error
)
copy _001.ans _tmp.out >nul 
check _001.in _tmp.out _001.ans 
IF errorlevel 1 (
  echo Test 1: 'check _001.in _tmp.out _001.ans' returned non-zero exit code!
  goto error
)

echo Copying tests to statement/examples 
mkdir ..\statement\examples 
echo Test 1 
copy _001.in ..\statement\examples\_001.in >nul 
copy _001.ans ..\statement\examples\_001.ans >nul 
echo Problem built. 
cd .. 
echo \FilesWithExample{examples/_001.in}{examples/_001.ans}%%  >statement/_examples.tex
echo Examples created. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
