@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Building ./c_pots (id pots) 
echo =================================== 
IF EXIST work rmdir /q /s work 
IF EXIST tests-ready rmdir /q /s tests-ready 
mkdir work 
copy tests\*.* work\*.* 
cd work 

echo Running test generation script(s)... 
rem Next text has been translated from file(s) do_all.d 


copy 01.hand 01 >nul 


copy 02.hand 02 >nul 


copy 03.hand 03 >nul 


copy 04.hand 04 >nul 


copy 05.hand 05 >nul 


g++ -I..\..\..\res\testlib -O2 gen_all_coverable.cpp -o gen_all_coverable.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_all_coverable.cpp -o gen_all_coverable.exe' returned non-zero exit code!
  goto error
)

g++ -I..\..\..\res\testlib -O2 gen_all_the_same.cpp -o gen_all_the_same.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_all_the_same.cpp -o gen_all_the_same.exe' returned non-zero exit code!
  goto error
)

g++ -I..\..\..\res\testlib -O2 gen_rand.cpp -o gen_rand.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_rand.cpp -o gen_rand.exe' returned non-zero exit code!
  goto error
)

g++ -I..\..\..\res\testlib -O2 gen_inc_dec.cpp -o gen_inc_dec.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_inc_dec.cpp -o gen_inc_dec.exe' returned non-zero exit code!
  goto error
)

g++ -I..\..\..\res\testlib -O2 gen_inc_dec2.cpp -o gen_inc_dec2.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 gen_inc_dec2.cpp -o gen_inc_dec2.exe' returned non-zero exit code!
  goto error
)

gen_rand  11 10 12  >06
IF errorlevel 1 (
  echo 'gen_rand  11 10 12' returned non-zero exit code!
  goto error
)

gen_rand  12 23 22  >07
IF errorlevel 1 (
  echo 'gen_rand  12 23 22' returned non-zero exit code!
  goto error
)

gen_rand  13 57 44  >08
IF errorlevel 1 (
  echo 'gen_rand  13 57 44' returned non-zero exit code!
  goto error
)

gen_rand  14 33 19  >09
IF errorlevel 1 (
  echo 'gen_rand  14 33 19' returned non-zero exit code!
  goto error
)

gen_rand  15 100 100  >10
IF errorlevel 1 (
  echo 'gen_rand  15 100 100' returned non-zero exit code!
  goto error
)

gen_rand  16 555 550  >11
IF errorlevel 1 (
  echo 'gen_rand  16 555 550' returned non-zero exit code!
  goto error
)

gen_all_the_same  1 1000 1000 999  >12
IF errorlevel 1 (
  echo 'gen_all_the_same  1 1000 1000 999' returned non-zero exit code!
  goto error
)

gen_all_the_same  1000 1 1 1000  >13
IF errorlevel 1 (
  echo 'gen_all_the_same  1000 1 1 1000' returned non-zero exit code!
  goto error
)

gen_all_the_same  1000 1 1000 1000  >14
IF errorlevel 1 (
  echo 'gen_all_the_same  1000 1 1000 1000' returned non-zero exit code!
  goto error
)

gen_all_the_same  1000 1000 1000 999  >15
IF errorlevel 1 (
  echo 'gen_all_the_same  1000 1000 1000 999' returned non-zero exit code!
  goto error
)

gen_rand  1 390 500  >16
IF errorlevel 1 (
  echo 'gen_rand  1 390 500' returned non-zero exit code!
  goto error
)

gen_rand  2 490 500  >17
IF errorlevel 1 (
  echo 'gen_rand  2 490 500' returned non-zero exit code!
  goto error
)

gen_rand  33 500 444  >18
IF errorlevel 1 (
  echo 'gen_rand  33 500 444' returned non-zero exit code!
  goto error
)

gen_rand  4 500 499  >19
IF errorlevel 1 (
  echo 'gen_rand  4 500 499' returned non-zero exit code!
  goto error
)

gen_rand  5 750 1000  >20
IF errorlevel 1 (
  echo 'gen_rand  5 750 1000' returned non-zero exit code!
  goto error
)

gen_rand  6 1000 750  >21
IF errorlevel 1 (
  echo 'gen_rand  6 1000 750' returned non-zero exit code!
  goto error
)

gen_rand  7 1000 1000  >22
IF errorlevel 1 (
  echo 'gen_rand  7 1000 1000' returned non-zero exit code!
  goto error
)

gen_rand  8 1000 1000  >23
IF errorlevel 1 (
  echo 'gen_rand  8 1000 1000' returned non-zero exit code!
  goto error
)

gen_rand  0 20 20  >24
IF errorlevel 1 (
  echo 'gen_rand  0 20 20' returned non-zero exit code!
  goto error
)

gen_rand  1 50 50  >25
IF errorlevel 1 (
  echo 'gen_rand  1 50 50' returned non-zero exit code!
  goto error
)

gen_inc_dec2  11 6 50 50  >26
IF errorlevel 1 (
  echo 'gen_inc_dec2  11 6 50 50' returned non-zero exit code!
  goto error
)

gen_inc_dec2  22 30 150 50  >27
IF errorlevel 1 (
  echo 'gen_inc_dec2  22 30 150 50' returned non-zero exit code!
  goto error
)

gen_inc_dec2  33 500 500 750  >28
IF errorlevel 1 (
  echo 'gen_inc_dec2  33 500 500 750' returned non-zero exit code!
  goto error
)

gen_inc_dec2  44 100 900 900  >29
IF errorlevel 1 (
  echo 'gen_inc_dec2  44 100 900 900' returned non-zero exit code!
  goto error
)

gen_inc_dec2  55 100 1000 1000  >30
IF errorlevel 1 (
  echo 'gen_inc_dec2  55 100 1000 1000' returned non-zero exit code!
  goto error
)

rem (End of translated text) 

echo Compiling solution, validator and checker... 
g++ -I..\..\..\res\testlib -O2 ..\pots_el.cpp -o pots_el.exe 
IF errorlevel 1 (
  echo 'g++ -I..\..\..\res\testlib -O2 ..\pots_el.cpp -o pots_el.exe' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\validate.dpr' returned non-zero exit code!
  goto error
)
fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr 
IF errorlevel 1 (
  echo 'fpc -Mdelphi -FE. -Fu..\..\..\res\testlib -Fu..\..\..\res ..\check.dpr' returned non-zero exit code!
  goto error
)

echo Building answer files, validating and checking them... 

echo Test 1 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 01 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 1: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 01.a >nul 
validate 01 01.a 
IF errorlevel 1 (
  echo Test 1: 'validate 01 01.a' returned non-zero exit code!
  goto error
)
check 01 pots.out 01.a 
IF errorlevel 1 (
  echo Test 1: 'check 01 pots.out 01.a' returned non-zero exit code!
  goto error
)

echo Test 2 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 02 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 2: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 02.a >nul 
validate 02 02.a 
IF errorlevel 1 (
  echo Test 2: 'validate 02 02.a' returned non-zero exit code!
  goto error
)
check 02 pots.out 02.a 
IF errorlevel 1 (
  echo Test 2: 'check 02 pots.out 02.a' returned non-zero exit code!
  goto error
)

echo Test 3 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 03 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 3: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 03.a >nul 
validate 03 03.a 
IF errorlevel 1 (
  echo Test 3: 'validate 03 03.a' returned non-zero exit code!
  goto error
)
check 03 pots.out 03.a 
IF errorlevel 1 (
  echo Test 3: 'check 03 pots.out 03.a' returned non-zero exit code!
  goto error
)

echo Test 4 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 04 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 4: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 04.a >nul 
validate 04 04.a 
IF errorlevel 1 (
  echo Test 4: 'validate 04 04.a' returned non-zero exit code!
  goto error
)
check 04 pots.out 04.a 
IF errorlevel 1 (
  echo Test 4: 'check 04 pots.out 04.a' returned non-zero exit code!
  goto error
)

echo Test 5 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 05 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 5: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 05.a >nul 
validate 05 05.a 
IF errorlevel 1 (
  echo Test 5: 'validate 05 05.a' returned non-zero exit code!
  goto error
)
check 05 pots.out 05.a 
IF errorlevel 1 (
  echo Test 5: 'check 05 pots.out 05.a' returned non-zero exit code!
  goto error
)

echo Test 6 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 06 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 6: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 06.a >nul 
validate 06 06.a 
IF errorlevel 1 (
  echo Test 6: 'validate 06 06.a' returned non-zero exit code!
  goto error
)
check 06 pots.out 06.a 
IF errorlevel 1 (
  echo Test 6: 'check 06 pots.out 06.a' returned non-zero exit code!
  goto error
)

echo Test 7 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 07 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 7: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 07.a >nul 
validate 07 07.a 
IF errorlevel 1 (
  echo Test 7: 'validate 07 07.a' returned non-zero exit code!
  goto error
)
check 07 pots.out 07.a 
IF errorlevel 1 (
  echo Test 7: 'check 07 pots.out 07.a' returned non-zero exit code!
  goto error
)

echo Test 8 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 08 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 8: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 08.a >nul 
validate 08 08.a 
IF errorlevel 1 (
  echo Test 8: 'validate 08 08.a' returned non-zero exit code!
  goto error
)
check 08 pots.out 08.a 
IF errorlevel 1 (
  echo Test 8: 'check 08 pots.out 08.a' returned non-zero exit code!
  goto error
)

echo Test 9 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 09 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 9: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 09.a >nul 
validate 09 09.a 
IF errorlevel 1 (
  echo Test 9: 'validate 09 09.a' returned non-zero exit code!
  goto error
)
check 09 pots.out 09.a 
IF errorlevel 1 (
  echo Test 9: 'check 09 pots.out 09.a' returned non-zero exit code!
  goto error
)

echo Test 10 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 10 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 10: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 10.a >nul 
validate 10 10.a 
IF errorlevel 1 (
  echo Test 10: 'validate 10 10.a' returned non-zero exit code!
  goto error
)
check 10 pots.out 10.a 
IF errorlevel 1 (
  echo Test 10: 'check 10 pots.out 10.a' returned non-zero exit code!
  goto error
)

echo Test 11 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 11 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 11: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 11.a >nul 
validate 11 11.a 
IF errorlevel 1 (
  echo Test 11: 'validate 11 11.a' returned non-zero exit code!
  goto error
)
check 11 pots.out 11.a 
IF errorlevel 1 (
  echo Test 11: 'check 11 pots.out 11.a' returned non-zero exit code!
  goto error
)

echo Test 12 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 12 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 12: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 12.a >nul 
validate 12 12.a 
IF errorlevel 1 (
  echo Test 12: 'validate 12 12.a' returned non-zero exit code!
  goto error
)
check 12 pots.out 12.a 
IF errorlevel 1 (
  echo Test 12: 'check 12 pots.out 12.a' returned non-zero exit code!
  goto error
)

echo Test 13 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 13 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 13: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 13.a >nul 
validate 13 13.a 
IF errorlevel 1 (
  echo Test 13: 'validate 13 13.a' returned non-zero exit code!
  goto error
)
check 13 pots.out 13.a 
IF errorlevel 1 (
  echo Test 13: 'check 13 pots.out 13.a' returned non-zero exit code!
  goto error
)

echo Test 14 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 14 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 14: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 14.a >nul 
validate 14 14.a 
IF errorlevel 1 (
  echo Test 14: 'validate 14 14.a' returned non-zero exit code!
  goto error
)
check 14 pots.out 14.a 
IF errorlevel 1 (
  echo Test 14: 'check 14 pots.out 14.a' returned non-zero exit code!
  goto error
)

echo Test 15 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 15 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 15: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 15.a >nul 
validate 15 15.a 
IF errorlevel 1 (
  echo Test 15: 'validate 15 15.a' returned non-zero exit code!
  goto error
)
check 15 pots.out 15.a 
IF errorlevel 1 (
  echo Test 15: 'check 15 pots.out 15.a' returned non-zero exit code!
  goto error
)

echo Test 16 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 16 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 16: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 16.a >nul 
validate 16 16.a 
IF errorlevel 1 (
  echo Test 16: 'validate 16 16.a' returned non-zero exit code!
  goto error
)
check 16 pots.out 16.a 
IF errorlevel 1 (
  echo Test 16: 'check 16 pots.out 16.a' returned non-zero exit code!
  goto error
)

echo Test 17 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 17 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 17: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 17.a >nul 
validate 17 17.a 
IF errorlevel 1 (
  echo Test 17: 'validate 17 17.a' returned non-zero exit code!
  goto error
)
check 17 pots.out 17.a 
IF errorlevel 1 (
  echo Test 17: 'check 17 pots.out 17.a' returned non-zero exit code!
  goto error
)

echo Test 18 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 18 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 18: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 18.a >nul 
validate 18 18.a 
IF errorlevel 1 (
  echo Test 18: 'validate 18 18.a' returned non-zero exit code!
  goto error
)
check 18 pots.out 18.a 
IF errorlevel 1 (
  echo Test 18: 'check 18 pots.out 18.a' returned non-zero exit code!
  goto error
)

echo Test 19 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 19 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 19: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 19.a >nul 
validate 19 19.a 
IF errorlevel 1 (
  echo Test 19: 'validate 19 19.a' returned non-zero exit code!
  goto error
)
check 19 pots.out 19.a 
IF errorlevel 1 (
  echo Test 19: 'check 19 pots.out 19.a' returned non-zero exit code!
  goto error
)

echo Test 20 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 20 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 20: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 20.a >nul 
validate 20 20.a 
IF errorlevel 1 (
  echo Test 20: 'validate 20 20.a' returned non-zero exit code!
  goto error
)
check 20 pots.out 20.a 
IF errorlevel 1 (
  echo Test 20: 'check 20 pots.out 20.a' returned non-zero exit code!
  goto error
)

echo Test 21 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 21 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 21: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 21.a >nul 
validate 21 21.a 
IF errorlevel 1 (
  echo Test 21: 'validate 21 21.a' returned non-zero exit code!
  goto error
)
check 21 pots.out 21.a 
IF errorlevel 1 (
  echo Test 21: 'check 21 pots.out 21.a' returned non-zero exit code!
  goto error
)

echo Test 22 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 22 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 22: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 22.a >nul 
validate 22 22.a 
IF errorlevel 1 (
  echo Test 22: 'validate 22 22.a' returned non-zero exit code!
  goto error
)
check 22 pots.out 22.a 
IF errorlevel 1 (
  echo Test 22: 'check 22 pots.out 22.a' returned non-zero exit code!
  goto error
)

echo Test 23 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 23 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 23: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 23.a >nul 
validate 23 23.a 
IF errorlevel 1 (
  echo Test 23: 'validate 23 23.a' returned non-zero exit code!
  goto error
)
check 23 pots.out 23.a 
IF errorlevel 1 (
  echo Test 23: 'check 23 pots.out 23.a' returned non-zero exit code!
  goto error
)

echo Test 24 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 24 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 24: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 24.a >nul 
validate 24 24.a 
IF errorlevel 1 (
  echo Test 24: 'validate 24 24.a' returned non-zero exit code!
  goto error
)
check 24 pots.out 24.a 
IF errorlevel 1 (
  echo Test 24: 'check 24 pots.out 24.a' returned non-zero exit code!
  goto error
)

echo Test 25 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 25 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 25: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 25.a >nul 
validate 25 25.a 
IF errorlevel 1 (
  echo Test 25: 'validate 25 25.a' returned non-zero exit code!
  goto error
)
check 25 pots.out 25.a 
IF errorlevel 1 (
  echo Test 25: 'check 25 pots.out 25.a' returned non-zero exit code!
  goto error
)

echo Test 26 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 26 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 26: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 26.a >nul 
validate 26 26.a 
IF errorlevel 1 (
  echo Test 26: 'validate 26 26.a' returned non-zero exit code!
  goto error
)
check 26 pots.out 26.a 
IF errorlevel 1 (
  echo Test 26: 'check 26 pots.out 26.a' returned non-zero exit code!
  goto error
)

echo Test 27 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 27 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 27: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 27.a >nul 
validate 27 27.a 
IF errorlevel 1 (
  echo Test 27: 'validate 27 27.a' returned non-zero exit code!
  goto error
)
check 27 pots.out 27.a 
IF errorlevel 1 (
  echo Test 27: 'check 27 pots.out 27.a' returned non-zero exit code!
  goto error
)

echo Test 28 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 28 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 28: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 28.a >nul 
validate 28 28.a 
IF errorlevel 1 (
  echo Test 28: 'validate 28 28.a' returned non-zero exit code!
  goto error
)
check 28 pots.out 28.a 
IF errorlevel 1 (
  echo Test 28: 'check 28 pots.out 28.a' returned non-zero exit code!
  goto error
)

echo Test 29 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 29 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 29: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 29.a >nul 
validate 29 29.a 
IF errorlevel 1 (
  echo Test 29: 'validate 29 29.a' returned non-zero exit code!
  goto error
)
check 29 pots.out 29.a 
IF errorlevel 1 (
  echo Test 29: 'check 29 pots.out 29.a' returned non-zero exit code!
  goto error
)

echo Test 30 
IF EXIST pots.out del pots.out >nul  
IF EXIST pots.in del pots.in >nul  
copy 30 pots.in >nul 
pots_el  
IF errorlevel 1 (
  echo Test 30: 'pots_el ' returned non-zero exit code!
  goto error
)
copy pots.out 30.a >nul 
validate 30 30.a 
IF errorlevel 1 (
  echo Test 30: 'validate 30 30.a' returned non-zero exit code!
  goto error
)
check 30 pots.out 30.a 
IF errorlevel 1 (
  echo Test 30: 'check 30 pots.out 30.a' returned non-zero exit code!
  goto error
)

echo Copying tests to tests-ready 
mkdir ..\tests-ready 
echo Test 1 
copy 01 ..\tests-ready\01 >nul 
copy 01.a ..\tests-ready\01.a >nul 
echo Test 2 
copy 02 ..\tests-ready\02 >nul 
copy 02.a ..\tests-ready\02.a >nul 
echo Test 3 
copy 03 ..\tests-ready\03 >nul 
copy 03.a ..\tests-ready\03.a >nul 
echo Test 4 
copy 04 ..\tests-ready\04 >nul 
copy 04.a ..\tests-ready\04.a >nul 
echo Test 5 
copy 05 ..\tests-ready\05 >nul 
copy 05.a ..\tests-ready\05.a >nul 
echo Test 6 
copy 06 ..\tests-ready\06 >nul 
copy 06.a ..\tests-ready\06.a >nul 
echo Test 7 
copy 07 ..\tests-ready\07 >nul 
copy 07.a ..\tests-ready\07.a >nul 
echo Test 8 
copy 08 ..\tests-ready\08 >nul 
copy 08.a ..\tests-ready\08.a >nul 
echo Test 9 
copy 09 ..\tests-ready\09 >nul 
copy 09.a ..\tests-ready\09.a >nul 
echo Test 10 
copy 10 ..\tests-ready\10 >nul 
copy 10.a ..\tests-ready\10.a >nul 
echo Test 11 
copy 11 ..\tests-ready\11 >nul 
copy 11.a ..\tests-ready\11.a >nul 
echo Test 12 
copy 12 ..\tests-ready\12 >nul 
copy 12.a ..\tests-ready\12.a >nul 
echo Test 13 
copy 13 ..\tests-ready\13 >nul 
copy 13.a ..\tests-ready\13.a >nul 
echo Test 14 
copy 14 ..\tests-ready\14 >nul 
copy 14.a ..\tests-ready\14.a >nul 
echo Test 15 
copy 15 ..\tests-ready\15 >nul 
copy 15.a ..\tests-ready\15.a >nul 
echo Test 16 
copy 16 ..\tests-ready\16 >nul 
copy 16.a ..\tests-ready\16.a >nul 
echo Test 17 
copy 17 ..\tests-ready\17 >nul 
copy 17.a ..\tests-ready\17.a >nul 
echo Test 18 
copy 18 ..\tests-ready\18 >nul 
copy 18.a ..\tests-ready\18.a >nul 
echo Test 19 
copy 19 ..\tests-ready\19 >nul 
copy 19.a ..\tests-ready\19.a >nul 
echo Test 20 
copy 20 ..\tests-ready\20 >nul 
copy 20.a ..\tests-ready\20.a >nul 
echo Test 21 
copy 21 ..\tests-ready\21 >nul 
copy 21.a ..\tests-ready\21.a >nul 
echo Test 22 
copy 22 ..\tests-ready\22 >nul 
copy 22.a ..\tests-ready\22.a >nul 
echo Test 23 
copy 23 ..\tests-ready\23 >nul 
copy 23.a ..\tests-ready\23.a >nul 
echo Test 24 
copy 24 ..\tests-ready\24 >nul 
copy 24.a ..\tests-ready\24.a >nul 
echo Test 25 
copy 25 ..\tests-ready\25 >nul 
copy 25.a ..\tests-ready\25.a >nul 
echo Test 26 
copy 26 ..\tests-ready\26 >nul 
copy 26.a ..\tests-ready\26.a >nul 
echo Test 27 
copy 27 ..\tests-ready\27 >nul 
copy 27.a ..\tests-ready\27.a >nul 
echo Test 28 
copy 28 ..\tests-ready\28 >nul 
copy 28.a ..\tests-ready\28.a >nul 
echo Test 29 
copy 29 ..\tests-ready\29 >nul 
copy 29.a ..\tests-ready\29.a >nul 
echo Test 30 
copy 30 ..\tests-ready\30 >nul 
copy 30.a ..\tests-ready\30.a >nul 
echo Problem built. 
cd .. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
