#!/bin/bash
# This file was automatically generated by daysper
# Please consider editing the original daysper script file(s) instead of this script
rm -f _daysper.log 

echo '===================================' 
echo 'Making examples for statements for  ./a_classics (id classics)' 
echo '===================================' 
echo 'Building examples' 
rm -rf ./work 
rm -rf ./statement/examples 
mkdir work 
cp tests/* work/ 
cd work 

echo 'Running test generation script(s)...' 
# Next text has been translated from file(s) do_st.d


cp st01.hand _001.in 

cp st01.hand.a _001.ans 


cp st02.hand _002.in 

cp st02.hand.a _002.ans 


cp st03.hand _003.in 

cp st03.hand.a _003.ans 


cp st04.hand _004.in 

cp st04.hand.a _004.ans 


# (End of translated text)

echo 'Compiling solution, validator and checker...' 
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../classics_pk.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../classics_pk.dpr' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../validate.dpr' returned non-zero exit code!" ; exit 1; }
fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr  || { echo "'fpc -Mdelphi -FE. -Fu../../../res/testlib -Fu../../../res ../check.dpr' returned non-zero exit code!" ; exit 1; }

echo 'Building answer files, validating and checking them...' 

echo 'Test 1' 
rm -f classics.out 
rm -f classics.in 
cp _001.in classics.in 
./classics_pk   || { echo "Test 1: './classics_pk ' returned non-zero exit code!" ; exit 1; }
./validate _001.in _001.ans  || { echo "Test 1: './validate _001.in _001.ans' returned non-zero exit code!" ; exit 1; }
./check _001.in classics.out _001.ans  || { echo "Test 1: './check _001.in classics.out _001.ans' returned non-zero exit code!" ; exit 1; }
cp _001.ans _tmp.out 
./check _001.in _tmp.out _001.ans  || { echo "Test 1: './check _001.in _tmp.out _001.ans' returned non-zero exit code!" ; exit 1; }

echo 'Test 2' 
rm -f classics.out 
rm -f classics.in 
cp _002.in classics.in 
./classics_pk   || { echo "Test 2: './classics_pk ' returned non-zero exit code!" ; exit 1; }
./validate _002.in _002.ans  || { echo "Test 2: './validate _002.in _002.ans' returned non-zero exit code!" ; exit 1; }
./check _002.in classics.out _002.ans  || { echo "Test 2: './check _002.in classics.out _002.ans' returned non-zero exit code!" ; exit 1; }
cp _002.ans _tmp.out 
./check _002.in _tmp.out _002.ans  || { echo "Test 2: './check _002.in _tmp.out _002.ans' returned non-zero exit code!" ; exit 1; }

echo 'Test 3' 
rm -f classics.out 
rm -f classics.in 
cp _003.in classics.in 
./classics_pk   || { echo "Test 3: './classics_pk ' returned non-zero exit code!" ; exit 1; }
./validate _003.in _003.ans  || { echo "Test 3: './validate _003.in _003.ans' returned non-zero exit code!" ; exit 1; }
./check _003.in classics.out _003.ans  || { echo "Test 3: './check _003.in classics.out _003.ans' returned non-zero exit code!" ; exit 1; }
cp _003.ans _tmp.out 
./check _003.in _tmp.out _003.ans  || { echo "Test 3: './check _003.in _tmp.out _003.ans' returned non-zero exit code!" ; exit 1; }

echo 'Test 4' 
rm -f classics.out 
rm -f classics.in 
cp _004.in classics.in 
./classics_pk   || { echo "Test 4: './classics_pk ' returned non-zero exit code!" ; exit 1; }
./validate _004.in _004.ans  || { echo "Test 4: './validate _004.in _004.ans' returned non-zero exit code!" ; exit 1; }
./check _004.in classics.out _004.ans  || { echo "Test 4: './check _004.in classics.out _004.ans' returned non-zero exit code!" ; exit 1; }
cp _004.ans _tmp.out 
./check _004.in _tmp.out _004.ans  || { echo "Test 4: './check _004.in _tmp.out _004.ans' returned non-zero exit code!" ; exit 1; }

echo 'Copying tests to statement/examples' 
mkdir ../statement/examples 
echo 'Test 1' 
cp _001.in ../statement/examples/_001.in 
cp _001.ans ../statement/examples/_001.ans 
echo 'Test 2' 
cp _002.in ../statement/examples/_002.in 
cp _002.ans ../statement/examples/_002.ans 
echo 'Test 3' 
cp _003.in ../statement/examples/_003.in 
cp _003.ans ../statement/examples/_003.ans 
echo 'Test 4' 
cp _004.in ../statement/examples/_004.in 
cp _004.ans ../statement/examples/_004.ans 
echo 'Problem built.' 
cd .. 
echo '\FilesWithExample{examples/_001.in}{examples/_001.ans}\FilesWithExample{examples/_002.in}{examples/_002.ans}\FilesWithExample{examples/_003.in}{examples/_003.ans}\FilesWithExample{examples/_004.in}{examples/_004.ans}%'  >statement/_examples.tex
echo 'Examples created.' 
