@echo off
rem This file was automatically generated by daysper 
rem Please consider editing the original daysper script file(s) instead of this script 
IF EXIST _daysper.log del _daysper.log >nul  

echo =================================== 
echo Making statement for  ./a_classics (id classics) 
echo =================================== 
call _generate_examples.cmd  
IF errorlevel 1 (
  echo '_generate_examples.cmd' returned non-zero exit code!
  goto error
)
IF EXIST work rmdir /q /s work 
IF EXIST statement-ready rmdir /q /s statement-ready 
mkdir work 
cd work 
echo \input{../../_prologue.tex}\import{../statement/}{classics.tex}\end{document}  >classics_full.tex
latex classics_full 
IF errorlevel 1 echo 'latex classics_full' returned non-zero exit code >> ../_daysper.log
latex classics_full 
IF errorlevel 1 echo 'latex classics_full' returned non-zero exit code >> ../_daysper.log
dvips classics_full 
IF errorlevel 1 echo 'dvips classics_full' returned non-zero exit code >> ../_daysper.log
dvipdfmx classics_full 
IF errorlevel 1 echo 'dvipdfmx classics_full' returned non-zero exit code >> ../_daysper.log
mkdir ..\statement-ready 
copy classics_full.ps ..\statement-ready\classics_full.ps >nul 
copy classics_full.pdf ..\statement-ready\classics_full.pdf >nul 
cd .. 
echo Statement created. 
goto end
:error
echo An error occured! Exiting
exit /b 1
:end
